#!/usr/bin/env python3
"""Build and verify BroCraft's static release from its original editable source."""
from pathlib import Path, PurePosixPath
import base64
import hashlib
import json
import lzma
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
PACKED_SHA = '980924a9dd5bb35b92d06ebba78c3af3325e14cabb6843fc418fd287f081d644'
SOURCE_SHA = '53db180d2279c37af2d28bb718d38ef84ae22f2fa97f94020975f80d17994b6c'


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def run(*args: str) -> None:
    subprocess.run(args, cwd=ROOT, check=True)


def main() -> None:
    bootstrap = ROOT / '.bootstrap'
    if (bootstrap / 'READY').exists():
        parts = [bootstrap / f'release-{i:02}.b64' for i in range(8)]
        packed = base64.b64decode(''.join(p.read_text().strip() for p in parts), validate=True)
        if digest(packed) != PACKED_SHA:
            raise ValueError('Source transfer checksum mismatch')
        raw = lzma.decompress(packed)
        if digest(raw) != SOURCE_SHA:
            raise ValueError('Original source checksum mismatch')
        files = json.loads(raw)
        if len(files) != 22:
            raise ValueError('Unexpected source file count')
        hashes = {}
        for name, text in files.items():
            path = PurePosixPath(name)
            if path.is_absolute() or '..' in path.parts or not isinstance(text, str):
                raise ValueError(f'Invalid source path: {name}')
            target = ROOT / name
            target.parent.mkdir(parents=True, exist_ok=True)
            data = text.encode('utf-8')
            target.write_bytes(data)
            hashes[name] = digest(data)
        (ROOT / 'SOURCE-IMPORT.json').write_text(json.dumps({
            'edition': 'BroCraft 1.2 Living World',
            'sourceBundleSha256': SOURCE_SHA,
            'files': hashes,
            'audio': 'Regenerated by the original deterministic composition scripts; not copied MP3 bytes.'
        }, indent=2) + '\n')
        print('Verified and imported all 22 original source files.', flush=True)

    audio_dir = ROOT / 'assets/audio'
    inputs = b''.join((ROOT / p).read_bytes() for p in (
        'tools/compose_score.py', 'tools/compose_foley.py', 'requirements-build.txt'))
    input_hash = digest(inputs)
    cache_file = ROOT / '.audio-build.json'
    cache = json.loads(cache_file.read_text()) if cache_file.exists() else {}
    valid = cache.get('inputSha256') == input_hash and bool(cache.get('assets'))
    if valid:
        valid = all((audio_dir / name).is_file() and digest((audio_dir / name).read_bytes()) == sha
                    for name, sha in cache['assets'].items())
    if not valid:
        run(sys.executable, 'tools/compose_score.py')
        run(sys.executable, 'tools/compose_foley.py')
        cache = {'inputSha256': input_hash, 'assets': {
            p.name: digest(p.read_bytes()) for p in sorted(audio_dir.iterdir())
            if p.suffix in ('.mp3', '.json')}}
        cache_file.write_text(json.dumps(cache, indent=2) + '\n')
    else:
        print('Reusing verified original audio assets.', flush=True)

    run('node', 'tests/core.test.cjs')
    results = json.loads((ROOT / 'tests/core-results.json').read_text())
    if results['tests'] != 22 or any(x['status'] != 'PASS' for x in results['results']):
        raise ValueError('Core test suite did not pass')
    bank = json.loads((audio_dir / 'living-world.json').read_text())
    score = json.loads((audio_dir / 'manifest.json').read_text())
    if len(bank['clips']) != 385 or score['durationSeconds'] != 128:
        raise ValueError('Incomplete sound bank or score')
    for clip in bank['clips'].values():
        if clip['offset'] < 0 or clip['duration'] <= 0 or clip['offset'] + clip['duration'] > bank['duration'] + .001:
            raise ValueError('Invalid foley clip boundary')
    durations = {}
    for stem in ('horizon', 'motion', 'titan', 'impact'):
        out = subprocess.check_output([
            'ffprobe', '-v', 'error', '-show_entries', 'format=duration',
            '-of', 'default=noprint_wrappers=1:nokey=1', str(audio_dir / f'{stem}.mp3')], text=True)
        durations[stem] = float(out.strip())
        if not 128 <= durations[stem] < 128.2:
            raise ValueError(f'Unexpected encoded stem duration: {stem}')

    run(sys.executable, 'build.py')
    html = (ROOT / 'index.html').read_bytes()
    text = html.decode('utf-8')
    if len(html) < 10_000_000 or 'const FOLEY_DATA=' not in text or 'const SOUNDTRACK_DATA=' not in text:
        raise ValueError('The generated page does not contain the full game and audio')
    if '/*__SCRIPT__*/' in text or '/*__CSS__*/' in text:
        raise ValueError('Unreplaced build template')
    scripts = re.findall(r'<script\b[^>]*>(.*?)</script\s*>', text, re.S | re.I)
    if not scripts:
        raise ValueError('Game script missing')
    for script in scripts:
        with tempfile.NamedTemporaryFile(suffix='.js', mode='w', encoding='utf-8') as tmp:
            tmp.write(script)
            tmp.flush()
            run('node', '--check', tmp.name)
    public = ROOT / 'public'
    public.mkdir(exist_ok=True)
    (public / 'index.html').write_bytes(html)
    report = {
        'edition': 'BroCraft 1.2 Living World',
        'htmlBytes': len(html), 'htmlSha256': digest(html),
        'coreTestsPassed': results['tests'], 'foleyClips': len(bank['clips']),
        'scoreSeconds': score['durationSeconds'], 'encodedStemSeconds': durations,
        'scriptSyntax': 'PASS',
        'verificationLimits': 'This build job does not test physical audio output, browser controls or persistent saves.'
    }
    (ROOT / 'BUILD-REPORT.json').write_text(json.dumps(report, indent=2) + '\n')
    if (bootstrap / 'READY').exists():
        shutil.rmtree(bootstrap)
    print(json.dumps(report, indent=2), flush=True)


if __name__ == '__main__':
    main()
