'use strict';
const DAY_LENGTH=900;
const $=id=>document.getElementById(id);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const DEFAULT_OPTIONS={distance:4,sensitivity:1,fov:76,resolution:1,bobbing:true,...AUDIO_DEFAULTS};
function loadOptions(){try{const saved=JSON.parse(localStorage.getItem('brocraft-options')||'{}');const options={...DEFAULT_OPTIONS,...saved};if(!saved.audioVersion&&saved.volume>0&&saved.volume<=.6)options.volume=AUDIO_DEFAULTS.volume;return normalizeControlOptions(normalizeAudioOptions(options));}catch{return normalizeControlOptions({...DEFAULT_OPTIONS});}}
class SaveStore{
 constructor(){this.db=null;this.fallback=false;this.ready=this.open();}
 open(){return new Promise(resolve=>{try{const req=indexedDB.open('BroCraftLocal',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('worlds'))req.result.createObjectStore('worlds',{keyPath:'id'});};req.onsuccess=()=>{this.db=req.result;this.db.onversionchange=()=>this.db.close();resolve();};req.onerror=()=>{this.fallback=true;resolve();};req.onblocked=()=>{this.fallback=true;resolve();};}catch{this.fallback=true;resolve();}});}
 async all(){await this.ready;if(this.db)return new Promise((resolve,reject)=>{const r=this.db.transaction('worlds').objectStore('worlds').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{return Object.values(JSON.parse(localStorage.getItem('brocraft-worlds-v1')||'{}'));}catch{return [];}}
 async save(data){await this.ready;if(this.db)return new Promise((resolve,reject)=>{const tx=this.db.transaction('worlds','readwrite');tx.objectStore('worlds').put(data);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||new Error('Save failed'));tx.onabort=()=>reject(tx.error||new Error('Save aborted'));});const all=JSON.parse(localStorage.getItem('brocraft-worlds-v1')||'{}');all[data.id]=data;localStorage.setItem('brocraft-worlds-v1',JSON.stringify(all));}
 async delete(id){await this.ready;if(this.db)return new Promise((resolve,reject)=>{const tx=this.db.transaction('worlds','readwrite');tx.objectStore('worlds').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});const all=JSON.parse(localStorage.getItem('brocraft-worlds-v1')||'{}');delete all[id];localStorage.setItem('brocraft-worlds-v1',JSON.stringify(all));}
}
function validateSave(s){
 const fail=m=>{throw new Error(m);},finite=(v,min,max)=>Number.isFinite(v)&&v>=min&&v<=max;
 if(!s||s.version!==1||(s.generatorVersion??1)!==1||typeof s.seed!=='string'||!['survival','creative'].includes(s.mode)||!Array.isArray(s.edits)||!Array.isArray(s.inventory))fail('This is not a compatible BroCraft save.');
 if(s.edits.length>500000||s.seed.length>80||typeof s.id!=='string'||!s.id.length||s.id.length>100||typeof s.name!=='string'||s.name.length>80)fail('This save has invalid world metadata or exceeds supported limits.');
 for(const v of s.edits)if(!Array.isArray(v)||v.length!==4||v.slice(0,3).some(n=>!Number.isInteger(n)||Math.abs(n)>1e7)||v[1]<1||v[1]>=HEIGHT||!Number.isInteger(v[3])||!BLOCKS[v[3]])fail('The save contains invalid block data.');
 const validStack=v=>v==null||(ITEMS[v.id]&&Number.isInteger(v.id)&&Number.isInteger(v.n)&&v.n>0&&v.n<=ITEMS[v.id].stack&&(!ITEMS[v.id].maxDurability||Number.isInteger(v.dur)&&v.dur>0&&v.dur<=ITEMS[v.id].maxDurability));
 if(s.inventory.length!==36||s.inventory.some(v=>!validStack(v)))fail('The save contains invalid inventory data.');
 const validPos=p=>p&&['x','y','z'].every(k=>finite(p[k],-1e7,1e7));
 if(!validPos(s.player)||!validPos(s.spawn)||!finite(s.player.health,0,20)||!finite(s.player.hunger,0,20)||!Number.isFinite(s.player.yaw)||!finite(s.player.pitch,-Math.PI/2,Math.PI/2))fail('The save contains invalid player data.');
 if(!Number.isInteger(s.selected)||s.selected<0||s.selected>8||!finite(s.time,0,1e12))fail('The save contains invalid time or hotbar data.');
 if(!Array.isArray(s.tiles)||s.tiles.length>100000)fail('The save contains invalid workstation data.');
 for(const entry of s.tiles){
  if(!Array.isArray(entry)||entry.length!==2||typeof entry[0]!=='string'||!/^[-]?\d+,\d+,[-]?\d+$/.test(entry[0]))fail('The save contains invalid workstation coordinates.');
  const pos=entry[0].split(',').map(Number),t=entry[1];
  if(pos.some(v=>!Number.isSafeInteger(v)||Math.abs(v)>1e7)||pos[1]<1||pos[1]>=HEIGHT||!t||!['chest','furnace'].includes(t.kind)||!Array.isArray(t.slots)||t.slots.length!==(t.kind==='chest'?27:3)||t.slots.some(v=>!validStack(v)))fail('The save contains invalid workstation contents.');
  if(t.kind==='furnace'&&(!finite(t.fuel,0,100000)||!finite(t.fuelMax,0,100000)||!finite(t.progress,0,8)||!Number.isInteger(t.recipeId)))fail('The save contains invalid furnace progress.');
 }
 if(!Array.isArray(s.drops)||s.drops.length>20000||s.drops.some(d=>!validStack(d)||!validPos(d)||!finite(d.age,0,301)))fail('The save contains invalid dropped items.');
 if(!Array.isArray(s.mobs)||s.mobs.length>1000||s.mobs.some(m=>!MOB_TYPES[m.type]||!validPos(m)||!finite(m.hp,0,MOB_TYPES[m.type].hp)||!Number.isFinite(m.yaw)))fail('The save contains invalid creatures.');
 if(!Array.isArray(s.achievements)||s.achievements.length>100||s.achievements.some(v=>typeof v!=='string'||v.length>50))fail('The save contains invalid journey data.');
 return s;
}
class Game{
 constructor(renderer){
  this.renderer=renderer;this.canvas=renderer.canvas;this.options=loadOptions();this.store=new SaveStore();this.sound=new Sound(this);this.controls=new Controls(this);this.active=false;this.loading=false;this.overlay='title';this.inventory=new Array(36).fill(null);this.selected=0;this.time=125;this.keys=new Set();this.mouseDown=false;this.rightDown=false;this.attackCooldown=0;this.placeCooldown=0;this.mine=null;this.target=null;this.mobTarget=null;this.swing=0;this.flash=0;this.itemLabelTime=0;this.debug=false;this.fps=60;this.frameMs=16;this.clock=0;this.last=0;this.uiTimer=0;this.autosave=0;this.spawnTimer=0;this.ambientTimer=0;this.streamTimer=0;this.saveInFlight=false;this.mobs=[];this.drops=[];this.particles=[];this.projectiles=[];this.meshes=new Map();this.mobMeshes=new Map();this.achievements=new Set();this.placed=0;this.mined=0;this.xp=0;this.showJourney=true;this.maxMobs=24;this.day=1;this.ui=null;this.pendingNew=false;this.invVersion=0;this.mode='survival';this.worldName='A little wilderness';this.worldId='';this.created=Date.now();this.eye=[0,40,0];this.dir=[0,0,-1];this.sun=1;this.daylight=1;this.sky=[.6,.77,.83];this.previewAngle=0;this.queue=[];this.required=[];this.readyToEnter=false;this.lastChunk='';this.flyTap=0;
  this.player=this.newPlayer({x:0,y:40,z:0});this.makeSceneAssets();this.initInputs();this.world=new VoxelWorld('first-light');this.attachWorld();this.spawn=this.world.findSpawn();this.player=this.newPlayer(this.spawn);this.previewCenter={...this.spawn};this.updateStream(true);this.renderer.resize(this.options.resolution);
 }
 newPlayer(p){return {...p,vx:0,vy:0,vz:0,yaw:0,pitch:0,height:1.8,grounded:false,health:20,hunger:20,air:20,invul:0,regen:0,starve:0,drown:0,fly:false,fallTop:p.y,footstep:0,jumpDelay:0,knockX:0,knockZ:0,hazard:0,bob:0};}
 attachWorld(){this.world.onDispose=c=>{c.mesh?.dispose();c.waterMesh?.dispose();};}
 makeSceneAssets(){const r=this.renderer;
  let g=new Geometry();for(let i=0;i<48;i++){const x=hash3(i,77,31)*500-250,z=hash3(i,67,81)*500-250,w=7+Math.floor(hash3(i,41,5)*17),d=4+Math.floor(hash3(i,99,6)*8);g.cube(x,92+hash3(i,7,9)*6,z,w,2,d,63,[.98,1,.96]);if(i%3===0)g.cube(x+3,94,z+1,w*.65,2,d*.7,63,[.98,1,.96]);}this.cloudMesh=r.mesh(g);
  for(const t of [60,61]){g=new Geometry();g.quad([[-.5,-.5,0],[.5,-.5,0],[.5,.5,0],[-.5,.5,0]],t,[1,1,1],1,0,null,true);this.meshes.set('celestial'+t,r.mesh(g));}
  g=new Geometry();for(let i=0;i<260;i++){const az=hash3(i,371,66)*Math.PI*2,el=hash3(i,194,22)*Math.PI*.5,pos=[Math.cos(az)*Math.cos(el)*235,Math.sin(el)*235,Math.sin(az)*Math.cos(el)*235],v=norm(pos),right=norm(cross([0,1,0],v)),up=cross(v,right),sz=.25+hash3(i,918,15)*.4;const p=(a,b)=>pos.map((n,k)=>n+right[k]*a*sz+up[k]*b*sz);g.quad([p(-1,-1),p(1,-1),p(1,1),p(-1,1)],63,[.8,.86,.8],1,0,null,true);}this.starMesh=r.mesh(g);
  g=new Geometry();g.quad([[-.5,.015,-.5],[-.5,.015,.5],[.5,.015,.5],[.5,.015,-.5]],79);this.shadowMesh=r.mesh(g);
  g=new Geometry();g.cube(-.12,-.27,-.1,.24,.52,.23,65,[1,1,1]);g.cube(-.126,-.28,-.105,.252,.19,.24,66,[1,1,1]);this.handMesh=r.mesh(g);
  this.particleMesh=r.mesh(new Geometry(),true);this.outlineMesh=r.mesh(new Geometry(),true);this.crackMesh=r.mesh(new Geometry(),true);
  g=new Geometry();g.cube(-.025,-.025,-.45,.05,.05,.9,100,[.8,.75,.6]);g.cube(-.06,-.045,-.49,.12,.09,.1,74);this.arrowMesh=r.mesh(g);
 }
 resetWorld(){this.world?.dispose();this.mobs=[];this.drops=[];this.particles=[];this.projectiles=[];this.queue=[];this.mine=null;this.target=null;this.mouseDown=false;this.keys.clear();}
 async beginWorld(save=null,config={}){
  if(save)validateSave(save);this.resetWorld();this.active=false;this.loading=true;this.readyToEnter=false;this.pendingNew=!save;this.pendingSoundcheck=!save&&!!config.soundcheck;this.overlay='loading';this.ui.page('loading');$('loading-title').textContent='Growing your world…';$('loading-detail').textContent='Shaping hills, carving caves, planting trees.';$('enter-world').classList.add('hidden');$('loading-progress').style.width='0%';
  this.mode=save?.mode||config.mode||'survival';this.worldName=save?.name||config.name||'My little wilderness';this.worldId=save?.id||'w-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);this.created=save?.created||Date.now();this.world=new VoxelWorld(save?.seed??config.seed??'first-light');this.attachWorld();this.world.loadEdits(save?.edits);if(save?.tiles)for(const [k,t] of save.tiles)this.world.tiles.set(k,structuredClone(t));
  this.spawn=save?.spawn?{...save.spawn}:this.world.findSpawn();this.player=this.newPlayer(save?.player?.health>0?save.player:this.spawn);if(save?.player?.health>0){this.player.health=clamp(save.player.health,1,20);this.player.hunger=clamp(save.player.hunger,0,20);this.player.yaw=Number.isFinite(save.player.yaw)?save.player.yaw:0;this.player.pitch=clamp(save.player.pitch||0,-1.55,1.55);this.player.fly=this.mode==='creative'&&!!save.player.fly;}
  this.time=save?.time??110;this.inventory=save?save.inventory.map(cloneStack):new Array(36).fill(null);this.selected=clamp(save?.selected||0,0,8);this.achievements=new Set(save?.achievements||[]);this.placed=save?.placed||0;this.mined=save?.mined||0;this.xp=save?.xp||0;this.showJourney=save?.showJourney??true;this.autosave=0;this.spawnTimer=0;
  if(!save&&this.mode==='creative'){[1,5,7,8,19,23,20,21,22].forEach((id,i)=>this.inventory[i]=stack(id,64));}
  this.restoreMobs=save?.mobs||[];this.restoreDrops=save?.drops||[];const cx=Math.floor(this.player.x/16),cz=Math.floor(this.player.z/16);this.required=[];for(let z=cz-1;z<=cz+1;z++)for(let x=cx-1;x<=cx+1;x++)this.required.push(key2(x,z));this.previewCenter={...this.player};this.updateStream(true);this.inventoryChanged();
 }
 finishLoading(){
  this.loading=false;this.readyToEnter=true;if(this.pendingNew)this.chooseClearing();this.safePlayerPosition();this.previewCenter={...this.player};this.spawn={...this.spawn};if(this.pendingNew){this.spawn={x:this.player.x,y:this.player.y,z:this.player.z};let nearest=null,dist=Infinity;for(const c of this.world.chunks.values())for(let z=0;z<16;z++)for(let x=0;x<16;x++){const wx=c.cx*16+x,wz=c.cz*16+z,y=this.world.column(wx,wz).h+1,id=this.world.get(wx,y,wz);const d=Math.hypot(wx+.5-this.player.x,wz+.5-this.player.z);if((id===5||id===30)&&d>2&&d<dist){nearest={x:wx+.5,z:wz+.5};dist=d;}}if(nearest){this.player.yaw=Math.atan2(nearest.x-this.player.x,-(nearest.z-this.player.z));this.player.pitch=-.05;}}
  for(const m of this.restoreMobs||[])if(MOB_TYPES[m.type]&&[m.x,m.y,m.z,m.hp].every(Number.isFinite))this.spawnMob(m.type,m.x,m.y,m.z,m);for(const d of this.restoreDrops||[])if(ITEMS[d.id]&&[d.x,d.y,d.z,d.n].every(Number.isFinite))this.spawnDrop(d.x,d.y,d.z,stack(d.id,d.n,d.dur),{age:d.age||0,delay:.5});
  if(this.pendingSoundcheck){this.buildSoundcheck();this.pendingSoundcheck=false;}if(!this.mobs.length)this.populate(8);$('loading-title').textContent='Your wilderness is ready.';$('loading-detail').textContent=this.mode==='creative'?'Every block is yours. Double-tap '+this.controls.label('jump')+' to fly.':'Find a tree. Make a tool. Leave your mark.';$('loading-progress').style.width='100%';$('enter-world').classList.remove('hidden');$('enter-world').focus();
 }
 enter(){if(!this.readyToEnter)return;this.active=true;this.readyToEnter=false;this.overlay=null;this.ui.hideMenus();$('hud').classList.remove('hidden');this.sound.start();this.lockPointer();this.ui.refreshHUD();if(this.pendingNew)this.ui.toast('Welcome to '+this.worldName,'Your first adventure starts with a tree.',5);this.save(false);}
 lockPointer(){try{const p=this.canvas.requestPointerLock();if(p?.catch)p.catch(()=>{if(this.active&&!this.overlay){this.pause();this.ui.toast('Click Back to exploring to capture the mouse.','Open the game as a full page, not inside a restricted preview.');}});}catch{this.pause();this.ui.toast('Mouse capture is unavailable.','Use the included localhost launcher in a desktop browser.');}}
 pause(){if(!this.active||this.overlay==='death')return;if(this.overlay==='inventory')this.ui.closeInventory(false);this.overlay='pause';this.keys.clear();this.mouseDown=false;this.rightDown=false;this.mine=null;document.exitPointerLock?.();this.ui.page('pause');$('pause-world-name').textContent=this.worldName+' · '+(this.mode==='creative'?'Creative':'Survival');}
 resume(){if(!this.active)return;this.overlay=null;this.ui.hideMenus();this.keys.clear();this.lockPointer();}
 chooseClearing(){const p=this.player,original={...p},trees=[];for(const c of this.world.chunks.values())for(let z=0;z<16;z++)for(let x=0;x<16;x++){const y=c.columns[x+z*16].h+1,id=c.data[chunkIndex(x,y,z)];if(id===5||id===30)trees.push([c.cx*16+x+.5,c.cz*16+z+.5]);}let best=null,bestScore=-Infinity;for(let dz=-13;dz<=13;dz++)for(let dx=-13;dx<=13;dx++){const x=Math.floor(original.x)+dx+.5,z=Math.floor(original.z)+dz+.5;if(!this.world.loaded(x,z))continue;const col=this.world.column(Math.floor(x),Math.floor(z)),y=col.h+1.01;if(col.h<=SEA+2||this.world.get(x,y-1,z)!==1||this.collides(x,y,z,.35,2.2))continue;let canopy=false;for(let yy=Math.floor(y)+2;yy<y+8;yy++)if([5,6,30,31].includes(this.world.get(x,yy,z))){canopy=true;break;}if(canopy)continue;let near=Infinity;for(const [tx,tz] of trees)near=Math.min(near,Math.hypot(tx-x,tz-z));if(near<3.5||near>12)continue;const slope=Math.abs(this.world.column(Math.floor(x)+2,Math.floor(z)).h-col.h)+Math.abs(this.world.column(Math.floor(x),Math.floor(z)+2).h-col.h);const score=-Math.abs(near-6)*2-Math.hypot(dx,dz)*.15-slope;if(score>bestScore){bestScore=score;best={x,y,z};}}if(best){Object.assign(p,best);p.fallTop=p.y;this.updateStream(true);}}
 safePlayerPosition(){const p=this.player;this.world.generate(Math.floor(p.x/16),Math.floor(p.z/16));if(!this.collides(p.x,p.y,p.z,.3,1.8)&&p.y>1)return;for(let rad=0;rad<=8;rad++)for(let dz=-rad;dz<=rad;dz++)for(let dx=-rad;dx<=rad;dx++){let x=Math.floor(p.x)+dx+.5,z=Math.floor(p.z)+dz+.5;this.world.generate(Math.floor(x/16),Math.floor(z/16));let y=this.world.ground(Math.floor(x),Math.floor(z))+.01;if(y>SEA&&this.world.get(x,y-1,z)!==24&&!this.collides(x,y,z,.3,1.8)){p.x=x;p.y=y;p.z=z;p.vy=0;p.fallTop=y;return;}}}
 initInputs(){
  window.addEventListener('resize',()=>this.renderer.resize(this.options.resolution));
  document.addEventListener('contextmenu',e=>e.preventDefault());
  document.addEventListener('mousemove',e=>{if(this.active&&!this.overlay&&document.pointerLockElement===this.canvas){this.player.yaw+=e.movementX*.00215*this.options.sensitivity;this.player.pitch=clamp(this.player.pitch-e.movementY*.00215*this.options.sensitivity,-1.55,1.55);}});
  document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==this.canvas&&this.active&&!this.overlay)this.pause();});
  window.addEventListener('blur',()=>{this.keys.clear();this.mouseDown=false;this.rightDown=false;if(this.active&&!this.overlay)this.pause();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.active)this.pause();});
  document.addEventListener('keydown',e=>{
   if(/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)||e.target.isContentEditable)return;
   const c=this.controls;
   if(e.ctrlKey||e.metaKey||e.altKey){
    // Best effort when delivered; browser-reserved chords can bypass page events.
    if(this.active&&!this.overlay&&e.code==='KeyW'&&(e.ctrlKey||e.metaKey))e.preventDefault();
    return;
   }
   if(e.code==='Escape'){if(this.overlay==='inventory'){e.preventDefault();this.ui.closeInventory(true);}else if(this.active&&!this.overlay)this.pause();else if(this.active&&['options','controls','audio'].includes(this.overlay))this.pause();return;}
   if(c.matches('inventory',e.code)&&this.active){e.preventDefault();if(e.repeat)return;if(this.overlay==='inventory')this.ui.closeInventory(true);else if(!this.overlay)this.ui.openInventory('craft');return;}
   if(c.matches('save',e.code)&&this.active){e.preventDefault();if(!e.repeat)this.save(true);return;}
   if(c.matches('debug',e.code)&&this.active){e.preventDefault();if(!e.repeat){this.debug=!this.debug;$('debug').classList.toggle('hidden',!this.debug);}return;}
   if(!this.active||this.overlay)return;
   if(c.matches('guide',e.code)){e.preventDefault();this.ui.openSubpage('controls');return;}
   if(c.matches('drop',e.code)&&!e.repeat){e.preventDefault();const s=this.held();if(s){this.spawnDrop(this.player.x+this.dir[0]*.7,this.player.y+1.2,this.player.z+this.dir[2]*.7,stack(s.id,1,s.dur),{vx:this.dir[0]*3,vy:2,vz:this.dir[2]*3,delay:1.4});if(this.mode!=='creative'&&--s.n<=0)this.inventory[this.selected]=null;this.inventoryChanged();}return;}
   if(/^Digit[1-9]$/.test(e.code)){e.preventDefault();this.select(Number(e.code.slice(5))-1);return;}
   if(c.matches('jump',e.code)&&!e.repeat&&this.mode==='creative'){const now=performance.now();if(now-this.flyTap<300){this.player.fly=!this.player.fly;this.player.vy=0;this.ui.toast(this.player.fly?'Flight enabled':'Flight disabled',this.player.fly?c.label('jump')+' to rise · '+c.label('crouch')+' to descend':'Double-tap '+c.label('jump')+' to take flight.');this.flyTap=0;}else this.flyTap=now;}
   if(['forward','back','left','right','jump','sprint','crouch'].some(a=>c.matches(a,e.code))){e.preventDefault();this.keys.add(e.code);}
  });
  document.addEventListener('keyup',e=>this.keys.delete(e.code));
  this.canvas.addEventListener('mousedown',e=>{if(!this.active||this.overlay)return;if(document.pointerLockElement!==this.canvas){this.lockPointer();return;}this.sound.start();if(e.button===0){this.mouseDown=true;this.swing=Math.max(this.swing,.001);this.attack();}if(e.button===2){this.rightDown=true;this.use();}if(e.button===1&&this.mode==='creative'&&this.target){const id=this.target.id;let i=this.inventory.findIndex(s=>s?.id===id);if(i>=0&&i<9)this.select(i);else{this.inventory[this.selected]=stack(id,64);this.inventoryChanged();}}});
  document.addEventListener('mouseup',e=>{if(e.button===0){this.mouseDown=false;this.mine=null;}if(e.button===2)this.rightDown=false;});
  this.canvas.addEventListener('wheel',e=>{if(!this.active||this.overlay)return;e.preventDefault();this.select(mod(this.selected+(e.deltaY>0?1:-1),9));},{passive:false});
  window.addEventListener('beforeunload',e=>{if(this.active){try{localStorage.setItem('brocraft-recovery',JSON.stringify(this.snapshot()));}catch{}if(this.options.closeGuard){e.preventDefault();e.returnValue='';}}});
 }
 held(){return this.inventory[this.selected];}
 select(n){this.selected=n;this.mine=null;this.inventoryChanged();this.itemLabelTime=2.2;this.ui?.showItemName();this.sound.play('ui');}
 inventoryChanged(){this.invVersion++;this.ui?.refreshInventory();this.ui?.refreshHotbar();this.ui?.updateJourney();}
 award(id){if(!this.achievements.has(id)){this.achievements.add(id);this.ui?.updateJourney();}}
 collides(x,y,z,r=.3,h=1.8){const minX=Math.floor(x-r+.001),maxX=Math.floor(x+r-.001),minY=Math.floor(y+.001),maxY=Math.floor(y+h-.001),minZ=Math.floor(z-r+.001),maxZ=Math.floor(z+r-.001);for(let yy=minY;yy<=maxY;yy++)for(let zz=minZ;zz<=maxZ;zz++)for(let xx=minX;xx<=maxX;xx++){const id=this.world.get(xx,yy,zz),b=BLOCKS[id];if(b.solid&&y+h>yy&&y<yy+(b.shape==='bed'?.48:1))return true;}return false;}
 floorSupported(x,y,z){for(const dx of [-.26,.26])for(const dz of [-.26,.26])if(this.world.solid(x+dx,y-.09,z+dz))return true;return false;}
 movePlayerAxis(axis,amount){const p=this.player,steps=Math.max(1,Math.ceil(Math.abs(amount)/.15)),inc=amount/steps;for(let i=0;i<steps;i++){const old=p[axis];p[axis]+=inc;if(axis!=='y'&&!this.world.loaded(p.x,p.z)){p[axis]=old;return false;}if(axis!=='y'&&this.controls.held('crouch')&&p.grounded&&!p.fly&&!this.floorSupported(p.x,p.y,p.z)){p[axis]=old;return false;}if(this.collides(p.x,p.y,p.z,.3,p.height)){if(axis!=='y'&&p.grounded&&!this.controls.held('crouch')&&!this.collides(p.x,p.y+.55,p.z,.3,p.height)){p.y+=.55;continue;}p[axis]=old;return false;}}return true;}
 updatePlayer(dt){const p=this.player,input=!this.overlay,oldGround=p.grounded,oldWater=!!p.inWater;const foot=this.world.get(p.x,p.y+.15,p.z),head=this.world.get(p.x,p.y+p.height-.13,p.z);p.inWater=foot===9;p.underwater=head===9;p.invul=Math.max(0,p.invul-dt);p.jumpDelay=Math.max(0,p.jumpDelay-dt);p.hazard=Math.max(0,p.hazard-dt);
  const sneak=input&&this.controls.held('crouch');p.crouching=sneak;if(sneak&&!p.fly)p.height=1.5;else if(!this.collides(p.x,p.y,p.z,.3,1.8))p.height=1.8;
  let forward=input?((this.controls.held('forward')?1:0)-(this.controls.held('back')?1:0)):0,strafe=input?((this.controls.held('right')?1:0)-(this.controls.held('left')?1:0)):0;const mag=Math.hypot(forward,strafe);if(mag>1){forward/=mag;strafe/=mag;}const sprint=input&&!sneak&&(this.controls.held('sprint'))&&(p.hunger>6||this.mode==='creative')&&forward>0;p.sprinting=!!sprint;
  let speed=p.fly?(sprint?15:8):p.inWater?2.1:sneak?1.4:sprint?5.65:4.3;const dx=(Math.sin(p.yaw)*forward+Math.cos(p.yaw)*strafe)*speed,dz=(-Math.cos(p.yaw)*forward+Math.sin(p.yaw)*strafe)*speed;const acc=p.fly?9:p.inWater?6:p.grounded?15:5;p.vx=lerp(p.vx,dx,Math.min(1,dt*acc));p.vz=lerp(p.vz,dz,Math.min(1,dt*acc));p.knockX*=Math.exp(-dt*7);p.knockZ*=Math.exp(-dt*7);
  if(p.fly){const up=input&&this.controls.held('jump')?1:0,down=sneak?1:0;p.vy=lerp(p.vy,(up-down)*speed,Math.min(1,dt*8));}
  else if(p.inWater){p.vy=lerp(p.vy,input&&this.controls.held('jump')?(p.underwater?3.5:5.3):-.65,Math.min(1,dt*4));p.fallTop=p.y;}
  else{p.vy=Math.max(-36,p.vy-24*dt);if(input&&this.controls.held('jump')&&p.grounded&&p.jumpDelay<=0){p.vy=8.4;p.grounded=false;p.jumpDelay=.25;if(this.mode==='survival')p.hunger=Math.max(0,p.hunger-(sprint?.12:.05));}}
  this.movePlayerAxis('x',(p.vx+p.knockX)*dt);this.movePlayerAxis('z',(p.vz+p.knockZ)*dt);const vertical=this.movePlayerAxis('y',p.vy*dt);if(!vertical){if(p.vy<0)p.grounded=true;p.vy=0;}else p.grounded=this.collides(p.x,p.y-.045,p.z,.3,p.height);if(!p.grounded)p.fallTop=Math.max(p.fallTop,p.y);else if(!oldGround){const fall=p.fallTop-p.y;if(fall>.6&&!p.inWater&&!p.fly){this.sound.event('land',{level:Math.min(.7,.15+fall*.1)});this.sound.material('step',this.world.get(p.x,p.y-.12,p.z),{level:.4});}if(fall>3.3&&!p.inWater&&!p.fly)this.hurt(Math.floor((fall-3)*2),'a hard landing');p.fallTop=p.y;}else p.fallTop=p.y;
  if(p.y<-.5){p.y=3;this.hurt(20,'the deep world');}if(p.y>HEIGHT+80){p.y=HEIGHT+80;p.vy=0;}
  const moving=Math.hypot(p.vx,p.vz);p.bob+=dt*moving*2.4;p.footstep+=dt*moving;if(p.footstep>2.15&&p.grounded&&!p.fly&&moving>1){this.sound.play('step',this.world.get(p.x,p.y-.12,p.z),{level:sneak?.22:sprint?.68:.49});p.footstep=0;}if(p.inWater!==oldWater)this.sound.play('splash');if(p.inWater&&moving>.8){p.swimSound=(p.swimSound||0)+dt;if(p.swimSound>.62){p.swimSound=0;this.sound.material('step','water',{level:.33});}}
  if(this.mode==='survival'){
   p.hunger=Math.max(0,p.hunger-dt*(sprint?.048:.012));if(p.hunger>=17&&p.health<20){p.regen+=dt;if(p.regen>=4){p.regen=0;p.health=Math.min(20,p.health+1);p.hunger=Math.max(0,p.hunger-.3);}}else p.regen=0;
   if(p.hunger<=0){p.starve+=dt;if(p.starve>=5){p.starve=0;if(p.health>1)this.hurt(1,'hunger');}}else p.starve=0;
   if(p.underwater){p.air=Math.max(0,p.air-dt);if(p.air<=0){p.drown+=dt;if(p.drown>1.5){p.drown=0;this.hurt(2,'running out of air');}}}else{p.air=Math.min(20,p.air+dt*5);p.drown=0;}
   let cactus=false;for(const [ox,oz] of [[.37,0],[-.37,0],[0,.37],[0,-.37]])if(this.world.get(p.x+ox,p.y+.5,p.z+oz)===24)cactus=true;
   if(p.hazard<=0&&(foot===34||head===34||cactus)){this.hurt(cactus?1:4,cactus?'a cactus':'lava');p.hazard=.8;}
  }
 }
 hurt(amount,reason='a wild creature',knock=null){const p=this.player;if(this.mode==='creative'||p.invul>0||p.health<=0||!this.active)return;p.health=Math.max(0,p.health-amount);p.invul=.65;this.flash=.9;this.sound.play('hurt');if(knock){p.knockX=knock[0];p.knockZ=knock[1];p.vy=Math.max(p.vy,3.2);}this.ui.refreshHUD();if(p.health<=0)this.die(reason);}
 die(reason){if(this.overlay==='inventory')this.ui.closeInventory(false);const p=this.player;for(const s of this.inventory)if(s)this.spawnDrop(p.x,p.y+.8,p.z,s,{delay:1.5});this.inventory.fill(null);this.inventoryChanged();this.mouseDown=false;this.keys.clear();this.overlay='death';document.exitPointerLock?.();this.ui.page('death');$('death-reason').textContent='Your adventure was interrupted by '+reason+'.';$('death-coords').textContent=`Your items are at ${Math.floor(p.x)}, ${Math.floor(p.y)}, ${Math.floor(p.z)}.`;this.save(false);}
 respawn(){this.player=this.newPlayer(this.spawn);this.safePlayerPosition();this.overlay=null;this.ui.hideMenus();this.lockPointer();this.inventoryChanged();this.ui.refreshHUD();this.updateStream(true);this.save(false);}
 updateCamera(){const p=this.player;const bob=this.options.bobbing&&p.grounded&&!p.fly&&Math.hypot(p.vx,p.vz)>.5?Math.sin(p.bob*2)*.035:0;this.eye=[p.x,p.y+p.height-.18+bob,p.z];this.dir=[Math.sin(p.yaw)*Math.cos(p.pitch),Math.sin(p.pitch),-Math.cos(p.yaw)*Math.cos(p.pitch)];}
 updateTarget(){this.target=voxelRay(this.world,this.eye,this.dir,this.mode==='creative'?7:5);let max=Math.min(this.target?.distance??7,this.mode==='creative'?6:3.25);this.mobTarget=null;for(const m of this.mobs){if(m.hp<=0)continue;const def=MOB_TYPES[m.type],t=rayAABB(this.eye,this.dir,[m.x-def.r,m.y,m.z-def.r],[m.x+def.r,m.y+def.h,m.z+def.r],max);if(t!==null){this.mobTarget=m;max=t;}}if(this.mobTarget)this.target=null;}
 attack(){if(this.attackCooldown>0||this.overlay)return;this.updateTarget();const s=this.held(),d=ITEMS[s?.id];this.swing=.001;if(!this.target)this.sound.event('swish',{level:.32});if(this.mobTarget){this.attackCooldown=d?.tool==='sword'?.34:.46;this.hitMob(this.mobTarget,d?.damage||1);if(d?.maxDurability)this.wearTool();this.mine=null;}}
 wearTool(){const s=this.held();if(this.mode==='creative'||!s||!ITEMS[s.id].maxDurability)return;s.dur--;if(s.dur<=0){const name=ITEMS[s.id].name;this.inventory[this.selected]=null;this.sound.play('tool-break');this.ui.toast(name+' broke.','Craft a replacement at your workbench.');}this.inventoryChanged();}
 miningTime(id){if(this.mode==='creative')return .075;const b=BLOCKS[id],tool=ITEMS[this.held()?.id];if(!Number.isFinite(b.hardness))return Infinity;let speed=tool?.maxDurability&&tool.tool===b.tool?tool.speed:1;return Math.max(.06,b.hardness/speed);}
 updateInteraction(dt){this.attackCooldown=Math.max(0,this.attackCooldown-dt);this.placeCooldown=Math.max(0,this.placeCooldown-dt);if(this.overlay){this.mine=null;return;}this.updateTarget();if(this.mouseDown&&this.mobTarget){this.attack();this.mine=null;}else if(this.mouseDown&&this.target){const t=this.target,key=key3(t.x,t.y,t.z);if(!this.mine||this.mine.key!==key){this.mine={...t,key,progress:0,tick:0};this.swing=.001;}this.mine.progress+=dt/this.miningTime(t.id);this.mine.tick+=dt;if(this.mine.tick>.21){this.sound.play('mine',t.id,{pos:{x:t.x+.5,y:t.y+.5,z:t.z+.5},toolId:this.held()?.id});this.mine.tick=0;this.spawnParticles(t.x+.5,t.y+.6,t.z+.5,t.id,2,.6);}if(this.swing<=0)this.swing=.001;if(this.mine.progress>=1){this.breakBlock(t);this.mine=null;}}
  else this.mine=null;if(this.rightDown&&this.placeCooldown<=0)this.use();}
 breakBlock(t){const b=BLOCKS[t.id];if(t.id===10||!Number.isFinite(b.hardness)&&this.mode!=='creative')return;const held=ITEMS[this.held()?.id],harvest=this.mode==='creative'||!b.minTier||(held?.tool===b.tool&&held.tier>=b.minTier);const k=key3(t.x,t.y,t.z),tile=this.world.tiles.get(k);if(tile){for(const s of tile.slots)if(s)this.spawnDrop(t.x+.5,t.y+.5,t.z+.5,s);}
  if(this.mode==='survival'&&harvest){let drop=b.drop,n=t.id===28?2+Math.floor(Math.random()*2):t.id===15?3:1;if(drop)this.spawnDrop(t.x+.5,t.y+.5,t.z+.5,stack(drop,n));if(b.leaf&&Math.random()<.14)this.spawnDrop(t.x+.5,t.y+.5,t.z+.5,stack(114));if(t.id===5||t.id===30)this.award('timber');if(t.id===3||t.id===8)this.award('stone');this.xp+=t.id>=11&&t.id<=16?4:1;}else if(!harvest)this.ui.toast('This block needs a stronger pickaxe.','The block broke, but its resource was lost.',t.id);
  this.world.set(t.x,t.y,t.z,0);this.spawnParticles(t.x+.5,t.y+.5,t.z+.5,t.id,15,1.7);this.sound.play('break',t.id,{pos:{x:t.x+.5,y:t.y+.5,z:t.z+.5}});if(held?.maxDurability&&this.mode==='survival')this.wearTool();this.mined++;
  const above=this.world.get(t.x,t.y+1,t.z);if(BLOCKS[above]?.shape==='plant'||above===23){if(BLOCKS[above].drop&&this.mode==='survival')this.spawnDrop(t.x+.5,t.y+1.2,t.z+.5,stack(BLOCKS[above].drop));this.world.set(t.x,t.y+1,t.z,0);}this.ui.updateJourney();}
 use(){if(this.overlay||this.placeCooldown>0)return;this.updateTarget();this.placeCooldown=.23;this.swing=.001;const t=this.target,s=this.held(),def=ITEMS[s?.id];const sneaking=this.controls.held('crouch');
  if(t&&!sneaking){const b=BLOCKS[t.id],k=key3(t.x,t.y,t.z);if(t.id===28){this.world.set(t.x,t.y,t.z,25);this.spawnDrop(t.x+.5,t.y+.6,t.z+.5,stack(111,3));this.sound.play('break',28);this.award('food');return;}if(b.station==='bed'){this.spawn={x:t.x+.5,y:t.y+.5,z:t.z+.5};if(this.daylight<.45){this.time=Math.ceil(this.time/DAY_LENGTH)*DAY_LENGTH+90;this.mobs=this.mobs.filter(m=>!MOB_TYPES[m.type].hostile);this.player.health=Math.min(20,this.player.health+3);this.ui.toast('A new day begins.','Your respawn point is set.',36);this.save(false);}else this.ui.toast('Respawn point set.','Return after sunset to sleep.',36);return;}if(b.station==='craft'){this.ui.openInventory('workbench',k);return;}if(b.station==='furnace'||b.station==='chest'){if(!this.world.tiles.has(k))this.world.tiles.set(k,b.station==='furnace'?{kind:'furnace',slots:[null,null,null],fuel:0,fuelMax:0,progress:0,recipeId:0}:{kind:'chest',slots:new Array(27).fill(null)});this.ui.openInventory(b.station,k);return;}}
  if(def?.food&&(this.player.hunger<20||this.mode==='creative')){this.player.hunger=Math.min(20,this.player.hunger+def.food);if(this.mode==='survival'&&--s.n<=0)this.inventory[this.selected]=null;this.placeCooldown=.7;this.sound.play('eat');this.inventoryChanged();this.ui.refreshHUD();return;}
  if(!t||!def?.place)return;let x=t.x+t.normal[0],y=t.y+t.normal[1],z=t.z+t.normal[2];if(BLOCKS[t.id].replaceable){x=t.x;y=t.y;z=t.z;}const current=BLOCKS[this.world.get(x,y,z)],b=BLOCKS[def.place];if(y<1||y>=HEIGHT||!current.replaceable)return;const p=this.player;if(b.solid&&x<p.x+.3&&x+1>p.x-.3&&z<p.z+.3&&z+1>p.z-.3&&y<p.y+p.height&&y+(b.shape==='bed'?.48:1)>p.y)return;if((b.shape==='plant'||b.shape==='torch')&&!this.world.solid(x,y-1,z)){this.ui.toast('This needs solid ground beneath it.');return;}
  if(this.world.set(x,y,z,def.place)){if(this.mode==='survival'&&--s.n<=0)this.inventory[this.selected]=null;this.sound.play('place',def.place,{pos:{x:x+.5,y:y+.5,z:z+.5}});this.spawnParticles(x+.5,y+.6,z+.5,def.place,4,.7);this.placed++;if(this.placed>=12)this.award('shelter');this.inventoryChanged();}
 }
 spawnDrop(x,y,z,s,extra={}){if(!s)return;for(const d of this.drops)if(sameStack(d,s)&&d.n+s.n<=64&&Math.hypot(d.x-x,d.y-y,d.z-z)<1.1){d.n+=s.n;d.age=Math.min(d.age,extra.age||0);return d;}const d={...s,x,y,z,vx:(Math.random()-.5)*1.5,vy:2,vz:(Math.random()-.5)*1.5,age:0,delay:.55,spin:Math.random()*6.28,...extra};this.drops.push(d);return d;}
 updateDrops(dt){const p=this.player;for(let i=this.drops.length-1;i>=0;i--){const d=this.drops[i];d.age+=dt;d.delay-=dt;if(d.age>300){this.drops.splice(i,1);continue;}if(!this.world.loaded(d.x,d.z))continue;const water=this.world.get(d.x,d.y,d.z)===9;d.vy=water?lerp(d.vy,.4,dt*2):Math.max(-16,d.vy-18*dt);let nx=d.x+d.vx*dt,nz=d.z+d.vz*dt;if(!this.world.solid(nx,d.y,nz)){d.x=nx;d.z=nz;}d.y+=d.vy*dt;const by=Math.floor(d.y-.13);if(this.world.solid(d.x,by,d.z)&&d.vy<0){d.y=by+1.15;d.vy=0;d.vx*=.8;d.vz*=.8;}if(d.y<0){d.y=2;d.vy=0;}d.spin+=dt*.9;
   const dist=Math.hypot(d.x-p.x,d.y-(p.y+.7),d.z-p.z);if(d.delay<=0&&dist<1.55&&p.health>0){const left=addStack(this.inventory,d);if(left<d.n){this.sound.play('pickup');if(d.id===5||d.id===30)this.award('timber');if(d.id===8)this.award('stone');if(ITEMS[d.id].food)this.award('food');this.itemLabelTime=1.8;this.ui.showItemName('+'+(d.n-left)+' '+ITEMS[d.id].name);d.n=left;if(!left)this.drops.splice(i,1);this.inventoryChanged();}}
  }}
 spawnParticles(x,y,z,id,n=12,power=1){for(let i=0;i<n;i++){if(this.particles.length>230)this.particles.shift();this.particles.push({x,y,z,vx:(Math.random()-.5)*4*power,vy:(Math.random()*3+.5)*power,vz:(Math.random()-.5)*4*power,life:.3+Math.random()*.45,max:.75,tile:BLOCKS[id]?blockTile(id,4):Assets.tileForItem[id]||63,size:.035+Math.random()*.045});}}
 updateParticles(dt){for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.life-=dt;if(p.life<=0){this.particles.splice(i,1);continue;}p.vy-=12*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;}}
 lightAt(x,y,z){const c=this.world.getChunk(Math.floor(x/16),Math.floor(z/16));if(!c?.light)return {sky:y>this.world.top(Math.floor(x),Math.floor(z))?1:.05,torch:0};const i=c.light.index(mod(Math.floor(x),16),clamp(Math.floor(y),0,HEIGHT-1),mod(Math.floor(z),16));return {sky:c.light.sky[i]/15,torch:c.light.torch[i]/15};}
 entityTint(x,y,z,hit=0){const l=this.lightAt(x,y,z),day=Math.max(.055,this.daylight);return [Math.max(.04,l.sky*day*.94,l.torch*1.12)/day,Math.max(.04,l.sky*day,l.torch*.86)/day*(hit>0?.42:1),Math.max(.04,l.sky*day*1.035,l.torch*.52)/day*(hit>0?.35:1),1];}
 updateStream(force=false){const p=this.player,cx=Math.floor(p.x/16),cz=Math.floor(p.z/16),key=key2(cx,cz)+':'+this.options.distance;if(!force&&key===this.lastChunk)return;this.lastChunk=key;const radius=this.active||this.loading||this.readyToEnter?this.options.distance:4;const jobs=[];for(let z=cz-radius;z<=cz+radius;z++)for(let x=cx-radius;x<=cx+radius;x++)if(!this.world.chunks.has(key2(x,z)))jobs.push({x,z,d:(x-cx)**2+(z-cz)**2});jobs.sort((a,b)=>a.d-b.d);this.queue=jobs;this.world.unload(cx,cz,radius+2);}
 processChunks(){const start=performance.now();let generated=0;while(this.queue.length&&generated<2&&performance.now()-start<5){const q=this.queue.shift();this.world.generate(q.x,q.z);generated++;}let candidates=[...this.world.dirty].map(k=>this.world.chunks.get(k)).filter(Boolean);const p=this.player;candidates.sort((a,b)=>(a.cx*16+8-p.x)**2+(a.cz*16+8-p.z)**2-((b.cx*16+8-p.x)**2+(b.cz*16+8-p.z)**2));if(candidates.length)meshChunk(this.world,candidates[0],this.renderer);if(this.loading){const ready=this.required.filter(k=>this.world.chunks.get(k)?.mesh&&!this.world.chunks.get(k).dirty).length;const progress=ready/this.required.length;$('loading-progress').style.width=Math.round(progress*100)+'%';if(progress===1)this.finishLoading();}if(!this.active&&!this.loading&&!this.readyToEnter)$('footer-status').textContent=this.queue.length?'Growing the Overworld…':'YOUR NEXT ADVENTURE IS ONE CLICK AWAY';}
 snapshot(){const p=this.player;const data={version:1,generatorVersion:1,id:this.worldId,name:this.worldName,seed:this.world.seed,mode:this.mode,created:this.created,updated:Date.now(),time:this.time,player:{x:p.x,y:p.y,z:p.z,yaw:p.yaw,pitch:p.pitch,health:p.health,hunger:p.hunger,fly:p.fly},spawn:{...this.spawn},inventory:this.inventory.map(cloneStack),selected:this.selected,edits:this.world.serializedEdits(),tiles:[...this.world.tiles].map(([k,t])=>[k,structuredClone(t)]),achievements:[...this.achievements],placed:this.placed,mined:this.mined,xp:this.xp,showJourney:this.showJourney,mobs:this.mobs.map(m=>({type:m.type,x:m.x,y:m.y,z:m.z,hp:Math.max(0,m.hp),yaw:m.yaw})),drops:this.drops.map(d=>({id:d.id,n:d.n,dur:d.dur,x:d.x,y:d.y,z:d.z,age:d.age}))};if(this.ui?.station){for(const s of [...this.ui.craftGrid,this.ui.cursor])if(s){const left=addStack(data.inventory,s);if(left)data.drops.push({id:s.id,n:left,dur:s.dur,x:p.x,y:p.y+.8,z:p.z,age:0});}}return data;}
 async save(notify=false){if(!this.worldId||this.saveInFlight)return false;this.saveInFlight=true;$('save-dot').className='saving';try{const data=this.snapshot();
   await this.store.save(data);$('save-dot').className='';$('save-dot').title='Saved '+new Date().toLocaleTimeString('en-GB');$('pause-save-status').textContent='Saved just now · Autosaves every 45 seconds.';try{localStorage.removeItem('brocraft-recovery');}catch{}if(notify)this.ui.toast('World saved.','Your changes are safe in this browser.',22);return true;}catch(error){$('save-dot').className='failed';$('pause-save-status').textContent='Saving failed. Export a backup to keep your world.';this.ui.toast('Could not save locally.','Export a backup from the pause menu. '+error.message);return false;}finally{this.saveInFlight=false;}}
 async quit(){if(this.overlay==='inventory')this.ui.closeInventory(false);const ok=await this.save(true);if(!ok){this.overlay='pause';this.ui.page('pause');return;}this.active=false;this.overlay='title';this.keys.clear();this.mouseDown=false;document.exitPointerLock?.();$('hud').classList.add('hidden');this.previewCenter={...this.player};this.previewAngle=0;this.ui.page('title');}
 update(dt){this.clock+=dt;this.attackCooldown=Math.max(0,this.attackCooldown);this.flash=Math.max(0,this.flash-dt*2);this.itemLabelTime=Math.max(0,this.itemLabelTime-dt);if(this.swing>0){this.swing+=dt*4.5;if(this.swing>=1)this.swing=0;}
  const sim=this.active&&(!this.overlay||this.overlay==='inventory');if(sim){this.time+=dt;this.updatePlayer(dt);this.updateCamera();this.updateInteraction(dt);this.updateDrops(dt);this.updateParticles(dt);this.updateMobs(dt);this.updateProjectiles(dt);for(const [k,t] of this.world.tiles)if(t.kind==='furnace'){const was=t.fuel>0;tickFurnace(t,dt);if(was!==(t.fuel>0)){const [x,,z]=k.split(',').map(Number);this.world.markDirty(Math.floor(x/16),Math.floor(z/16));}}
   this.autosave+=dt;if(this.autosave>=45){this.autosave=0;this.save(false);}this.ambientTimer+=dt;if(this.ambientTimer>22&&!this.sound.bank){this.ambientTimer=0;if(this.daylight>.6&&this.lightAt(this.player.x,this.player.y+1,this.player.z).sky>.5){this.sound.tone(1300,.13,.012,'sine',0,1700,'ambience');this.sound.tone(1650,.11,.01,'sine',.2,1400,'ambience');}else this.sound.hiss(1.5,.019,450,'ambience');}
  }
  this.streamTimer+=dt;if(this.streamTimer>.35){this.streamTimer=0;this.updateStream();}this.processChunks();this.uiTimer+=dt;if(this.uiTimer>.1){this.uiTimer=0;this.ui?.refreshHUD();if(this.overlay==='inventory')this.ui.refreshStation();}
 }
 draw(){const r=this.renderer;let eye,dir,fov=this.options.fov;const phase=mod(this.time,DAY_LENGTH)/DAY_LENGTH,theta=phase*Math.PI*2;this.sun=Math.sin(theta);this.daylight=clamp((this.sun+.17)/.45,.055,1);let dayColor=[.60,.77,.82],nightColor=[.055,.085,.13],sky=dayColor.map((v,i)=>lerp(nightColor[i],v,Math.pow(this.daylight,.7)));const sunset=(1-clamp(Math.abs(this.sun)/.3,0,1))*.38;sky=sky.map((v,i)=>lerp(v,[.83,.59,.42][i],sunset));
  if(this.active){this.updateCamera();eye=this.eye;dir=this.dir;fov+=this.player.sprinting?5:0;}else{const c=this.previewCenter;this.previewAngle+=.00035;const ang=this.previewAngle+.55,dist=24;eye=[c.x+Math.sin(ang)*dist,c.y+16,c.z+Math.cos(ang)*dist];const target=[c.x-3,c.y+1,c.z-9];dir=norm(sub(target,eye));fov=65;this.eye=eye;this.dir=dir;}
  if(this.active&&this.player.underwater)sky=[.13,.36,.47];this.sky=sky;r.begin(eye,dir,fov,sky,this.daylight,this.active&&this.player.underwater?14:this.options.distance*16+5);const right=norm(cross(dir,[0,1,0])),up=cross(right,dir);
  if(!(this.active&&this.player.underwater)){
   r.transparent(true);if(this.daylight<.8)r.draw(this.starMesh,M4.model(...eye),{unlit:true,noFog:true,tint:[1,1,1,(1-this.daylight)*.9]});r.transparent(false);
   for(const [tile,sign,size] of [[60,1,19],[61,-1,14]]){const pos=[eye[0]-Math.cos(theta)*170*sign,eye[1]+Math.sin(theta)*170*sign,eye[2]-75];if(pos[1]>eye[1]-30)r.draw(this.meshes.get('celestial'+tile),M4.billboard(pos,size,right,up),{unlit:true,noFog:true});}
   r.draw(this.cloudMesh,M4.model(Math.floor(eye[0]/240)*240+mod(this.time*.25,240)-120,0,Math.floor(eye[2]/240)*240));
  }
  const visible=[];for(const c of this.world.chunks.values())if(r.visible([c.cx*16,0,c.cz*16],[c.cx*16+16,HEIGHT,c.cz*16+16])){r.draw(c.mesh,M4.model(c.cx*16,0,c.cz*16));if(c.waterMesh)visible.push(c);}
  this.drawMobs();this.drawDrops();for(const a of this.projectiles)r.draw(this.arrowMesh,M4.model(a.x,a.y,a.z,Math.atan2(a.vx,-a.vz)),{tint:this.entityTint(a.x,a.y,a.z)});
  r.transparent(true);visible.sort((a,b)=>(b.cx*16-eye[0])**2+(b.cz*16-eye[2])**2-((a.cx*16-eye[0])**2+(a.cz*16-eye[2])**2));for(const c of visible)r.draw(c.waterMesh,M4.model(c.cx*16,0,c.cz*16));this.drawParticles(right,up);r.transparent(false);
  if(this.active&&!this.overlay){this.drawTarget();this.drawHand();}
 }
 drawTarget(){if(!this.target)return;const t=this.target,g=new Geometry(),e=.003,lo=[t.x-e,t.y-e,t.z-e],hi=[t.x+1+e,t.y+1+e,t.z+1+e];for(let a=0;a<3;a++)for(let u=0;u<2;u++)for(let v=0;v<2;v++){const other=[0,1,2].filter(x=>x!==a),p=[...lo],q=[...lo];p[other[0]]=q[other[0]]=u?hi[other[0]]:lo[other[0]];p[other[1]]=q[other[1]]=v?hi[other[1]]:lo[other[1]];q[a]=hi[a];g.line(p,q,[.12,.16,.1]);}this.outlineMesh.update(g);this.renderer.draw(this.outlineMesh,undefined,{lines:true,unlit:true});
  if(this.mine){const cracks=new Geometry(),n=t.normal,axis=n.findIndex(v=>v!==0),a=[0,1,2].filter(v=>v!==axis),base=[t.x+.5,t.y+.5,t.z+.5];if(axis>=0){base[axis]+=.504*n[axis];const stage=Math.floor(clamp(this.mine.progress,0,1)*8)+1;for(let i=0;i<stage*3;i++){const angle=hash3(i,5,8)*6.28,length=.12+hash3(i,2,1)*.33,points=[];for(let s=0;s<4;s++){const p=[...base],d=length*s/3;p[a[0]]+=Math.cos(angle)*d+(hash3(i,s,18)-.5)*.06;p[a[1]]+=Math.sin(angle)*d+(hash3(i,s,13)-.5)*.06;points.push(p);}for(let s=0;s<3;s++)cracks.line(points[s],points[s+1],[.1,.12,.08]);}this.crackMesh.update(cracks);this.renderer.draw(this.crackMesh,undefined,{lines:true,unlit:true});}}}
 itemMesh(id){if(this.meshes.has('item'+id))return this.meshes.get('item'+id);const d=ITEMS[id],g=new Geometry();if(d?.place&&BLOCKS[id]?.shape!=='plant'&&id!==23)g.cube(-.14,-.14,-.14,.28,.28,.28,f=>blockTile(id,f));else g.quad([[-.19,-.19,0],[.19,-.19,0],[.19,.19,0],[-.19,.19,0]],Assets.tileForItem[id]||63,[1,1,1],1,0,null,true);const mesh=this.renderer.mesh(g);this.meshes.set('item'+id,mesh);return mesh;}
 drawDrops(){for(const d of this.drops){if(!this.world.loaded(d.x,d.z)||Math.hypot(d.x-this.eye[0],d.z-this.eye[2])>70)continue;this.renderer.draw(this.itemMesh(d.id),M4.model(d.x,d.y+.07+Math.sin(this.clock*2+d.spin)*.045,d.z,d.spin),{tint:this.entityTint(d.x,d.y,d.z)});}}
 drawParticles(right,up){if(!this.particles.length)return;const g=new Geometry();for(const p of this.particles){const s=p.size*Math.min(1,p.life*5),pt=(a,b)=>[p.x+right[0]*a*s+up[0]*b*s,p.y+right[1]*a*s+up[1]*b*s,p.z+right[2]*a*s+up[2]*b*s],l=this.lightAt(p.x,p.y,p.z);g.quad([pt(-1,-1),pt(1,-1),pt(1,1),pt(-1,1)],p.tile,[1,1,1],l.sky,l.torch,null,true);}this.particleMesh.update(g);this.renderer.draw(this.particleMesh);}
 drawHand(){const r=this.renderer,p=this.player,swing=this.swing>0?Math.sin(this.swing*Math.PI):0,bob=this.options.bobbing&&p.grounded?Math.sin(p.bob)*Math.min(.018,Math.hypot(p.vx,p.vz)*.004):0;r.handView();r.draw(this.handMesh,M4.model(.43-swing*.16,-.43+swing*.07+bob,-.72-swing*.06,-.35-swing*.5,1),{noFog:true,tint:[1,1,1,1]});const s=this.held();if(s)r.draw(this.itemMesh(s.id),M4.model(.41-swing*.2,-.2+swing*.02+bob,-.77-swing*.1,-.6-swing*.7,s.id>=200?1.8:1.18),{noFog:true});}
 frame(now){if(!this.last)this.last=now;const raw=(now-this.last)/1000;this.last=now;const dt=Math.min(.1,Math.max(.001,raw));this.fps=lerp(this.fps,1/Math.max(.001,raw),.04);this.frameMs=lerp(this.frameMs,raw*1000,.05);try{this.update(dt);this.draw();}catch(error){console.error(error);this.ui?.fatal(error);return;}requestAnimationFrame(t=>this.frame(t));}
}
