'use strict';
class UI{
 constructor(game){this.g=game;game.ui=this;this.modeChoice='survival';this.returnPage='title';this.station=null;this.craftGrid=[];this.gridSize=2;this.cursor=null;this.bookMode='recipes';this.chosenRecipe=RECIPES[0];this.search='';this.slots=new Map();this.pointer={x:0,y:0};this.dragSource=null;this.dragButton=0;this.hotbarSlots=[];this.hudCache={};this.lastStationSignature='';this.createHotbar();this.bindMenus();this.bindAudio();this.bindInventory();this.renderOptions();game.controls.attachUI();this.bindFoley();this.recoverSave();}
 toast(title,detail='',id=null){const el=document.createElement('div');el.className='toast';el.innerHTML=(id&&Assets.icons[id]?`<img src="${Assets.icons[id]}" alt="">`:'')+`<div>${escapeHTML(title)}${detail?`<small>${escapeHTML(detail)}</small>`:''}</div>`;$('toasts').appendChild(el);while($('toasts').children.length>4)$('toasts').firstChild.remove();setTimeout(()=>{el.style.transition='opacity .4s,transform .4s';el.style.opacity=0;el.style.transform='translateX(15px)';setTimeout(()=>el.remove(),420);},4000);}
 fatal(error){$('error-screen').classList.remove('hidden');$('error-text').textContent=error.message||String(error);$('hud').classList.add('hidden');$('menu').classList.add('hidden');$('inventory-screen').classList.add('hidden');document.exitPointerLock?.();}
 page(name){if(name!=='audio'){this.g.sound.foleySolo=false;this.g.sound.tick();}if(name!=='controls')this.g.controls.captureAction=null;if(name==='controls')this.g.controls.render();if(name!=='audio')this.g.sound.sceneOverride='auto';for(const p of document.querySelectorAll('.menu-page'))p.classList.add('hidden');$(name+'-page').classList.remove('hidden');$('menu').classList.remove('hidden');$('menu').classList.toggle('modal',name!=='title');this.g.overlay=name==='pause'?'pause':name;if(name==='title')$('hud').classList.add('hidden');this.g.sound.play('ui');}
 hideMenus(){$('menu').classList.add('hidden');}
 openSubpage(name){this.returnPage=this.g.active?'pause':'title';if(this.g.active)this.g.pause();this.page(name);if(name==='options')this.renderOptions();if(name==='audio'){this.renderAudio();this.g.sound.foleySolo=!$('foley-lab').classList.contains('hidden')&&$('lab-solo').checked;this.g.sound.tick();}}
 bindMenus(){const g=this.g;
  $('singleplayer-btn').onclick=()=>this.showWorlds();$('new-world-btn').onclick=()=>this.page('create');$('worlds-create').onclick=()=>this.page('create');for(const b of document.querySelectorAll('.back-title'))b.onclick=()=>this.page('title');
  $('title-options').onclick=()=>this.openSubpage('options');$('title-controls').onclick=()=>this.openSubpage('controls');$('pause-options').onclick=()=>this.openSubpage('options');$('pause-controls').onclick=()=>this.openSubpage('controls');$('options-back').onclick=()=>this.page(this.returnPage);$('controls-back').onclick=()=>this.page(this.returnPage);
  $('random-seed').onclick=()=>{$('world-seed').value='wilderness-'+Math.random().toString(36).slice(2,9);g.sound.play('ui');};
  for(const b of document.querySelectorAll('.mode-card'))b.onclick=()=>{this.modeChoice=b.dataset.mode;for(const c of document.querySelectorAll('.mode-card'))c.classList.toggle('selected',c===b);$('mode-description').textContent=this.modeChoice==='survival'?'Find wood, make tools, and build before nightfall.':'All materials are available. Double-tap '+g.controls.label('jump')+' to fly.';g.sound.play('ui');};
  $('create-form').onsubmit=e=>{e.preventDefault();g.sound.start();g.beginWorld(null,{name:$('world-name').value.trim()||'My little wilderness',seed:$('world-seed').value.trim()||Math.random().toString(36).slice(2),mode:this.modeChoice}).catch(err=>this.fatal(err));};
  $('enter-world').onclick=()=>g.enter();$('resume-btn').onclick=()=>g.resume();$('save-now').onclick=()=>g.save(true);$('save-quit').onclick=()=>g.quit();$('death-quit').onclick=()=>g.quit();$('respawn-btn').onclick=()=>g.respawn();$('export-save').onclick=()=>this.exportSave();$('hide-journey').onclick=()=>{g.showJourney=false;this.updateJourney();};
  $('fullscreen-btn').onclick=()=>{const promise=document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();promise?.catch(()=>this.toast('Fullscreen is unavailable in this browser window.'));};
  $('import-world').onclick=()=>$('import-input').click();$('import-input').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>60*1024*1024)throw new Error('The save file is too large.');const data=validateSave(JSON.parse(await file.text()));data.id='w-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6);data.name=(String(data.name||'Imported world').slice(0,29)+' (imported)').slice(0,40);data.updated=Date.now();await g.store.save(data);this.toast('World imported.','A separate copy has been added to Your worlds.',22);this.showWorlds();}catch(err){this.toast('Import failed.',err.message);}};
  document.addEventListener('pointerdown',()=>g.sound.start());
 }
 bindAudio(){
  const g=this.g;
  for(const id of ['title-audio','pause-audio','options-audio'])$(id).onclick=()=>{g.sound.start();this.openSubpage('audio');};
  $('audio-back').onclick=()=>{g.sound.sceneOverride='auto';g.sound.tick();this.page(this.returnPage);};
  $('audio-start').onclick=()=>g.sound.retry();
  $('audio-test').onclick=()=>{g.sound.start();g.sound.play('boom');};
  $('audio-mute').onclick=()=>g.sound.toggleMute();
  $('audio-music').onchange=e=>{g.options.musicEnabled=e.target.checked;g.sound.applyOptions();this.persistOptions();};
  $('audio-scene-select').onchange=e=>{g.sound.sceneOverride=e.target.value;g.sound.tick();};
  for(const b of document.querySelectorAll('[data-audio-preset]'))b.onclick=()=>{g.sound.setPreset(b.dataset.audioPreset);this.renderAudio();};
  document.addEventListener('visibilitychange',()=>g.sound.visibility());
  document.addEventListener('keydown',e=>{
   if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)||e.target.isContentEditable)return;
   if(g.controls.matches('mute',e.code)||g.controls.matches('music',e.code)){e.preventDefault();g.sound.start();if(g.controls.matches('mute',e.code))g.sound.toggleMute();else g.sound.toggleMusic();}
  });
 }
 renderAudio(){
  const root=$('audio-fields');root.replaceChildren();
  const percent=v=>Math.round(v*100)+'%';
  const eq=v=>(10**(v/20)).toFixed(2)+'×';
  const specs=[['volume','Master',0,1,.01,percent],['musicVolume','Soundtrack',0,1,.01,percent],['sfxVolume','Sound effects',0,1,.01,percent],['wildlifeVolume','Creature voices',0,1,.01,percent],['ambienceVolume','World ambience',0,1,.01,percent],['bass','Bass / 110 Hz',-6,12,1,eq],['treble','Treble / 4.2 kHz',-6,12,1,eq],['intensity','Epic intensity',0,1,.01,percent],['caveReverb','Cave resonance',0,1,.01,percent]];
  for(const [key,label,min,max,step,format] of specs){const row=document.createElement('div');row.className='option-field sound-slider';const id='audio-'+key;row.innerHTML=`<label for="${id}">${label}<output>${format(this.g.options[key])}</output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${this.g.options[key]}">`;row.querySelector('input').oninput=e=>{this.g.options[key]=Number(e.target.value);row.querySelector('output').textContent=format(this.g.options[key]);this.g.sound.applyOptions();this.persistOptions();for(const b of document.querySelectorAll('[data-audio-preset]'))b.classList.remove('selected');};root.appendChild(row);}
  $('audio-music').checked=this.g.options.musicEnabled;$('audio-scene-select').value=this.g.sound.sceneOverride;
  for(const b of document.querySelectorAll('[data-audio-preset]')){const preset=AUDIO_PRESETS[b.dataset.audioPreset];b.classList.toggle('selected',Object.keys(AUDIO_DEFAULTS).filter(k=>!['muted','musicEnabled','audioVersion'].includes(k)).every(k=>this.g.options[k]===preset[k]));}
  this.g.sound.refreshUI();this.renderFoleyToggles();
 }
 async recoverSave(){try{const raw=localStorage.getItem('brocraft-recovery');if(!raw)return;const s=validateSave(JSON.parse(raw)),worlds=await this.g.store.all(),existing=worlds.find(w=>w.id===s.id);if(!existing||existing.updated<s.updated)await this.g.store.save(s);localStorage.removeItem('brocraft-recovery');}catch{/* A corrupt recovery record never replaces a valid saved world. */}}
 async showWorlds(){this.page('worlds');$('world-list').innerHTML='<p class="muted">Reading your local worlds…</p>';try{const worlds=(await this.g.store.all()).sort((a,b)=>b.updated-a.updated);$('world-list').replaceChildren();if(!worlds.length){$('world-list').innerHTML='<div class="empty-worlds"><div style="font-size:35px;color:#b5cf8b">◆</div>No footprints here. Yet.<br><span class="muted">Create a world and make yourself at home.</span></div>';return;}for(const w of worlds){const el=document.createElement('div');el.className='world-card';el.innerHTML=`<img class="world-icon" alt="" src="${Assets.icons[w.mode==='creative'?16:1]}"><div><strong>${escapeHTML(w.name||'Untitled world')}</strong><small>${w.mode==='creative'?'CREATIVE':'SURVIVAL'} · DAY ${Math.floor(w.time/DAY_LENGTH)+1} · ${escapeHTML(new Date(w.updated).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}))}</small><small>SEED ${escapeHTML(w.seed).slice(0,50)}</small></div><button class="primary play-world">Play →</button><button class="delete-world" title="Delete world">×</button>`;el.querySelector('.play-world').onclick=()=>{this.g.sound.start();this.g.beginWorld(w).catch(err=>this.toast('Could not load world.',err.message));};el.querySelector('.delete-world').onclick=async()=>{if(confirm(`Delete “${w.name}”? Exported backups will not be affected.`)){try{await this.g.store.delete(w.id);this.showWorlds();}catch(err){this.toast('Could not delete world.',err.message);}}};$('world-list').appendChild(el);}}catch(err){$('world-list').innerHTML='<p class="muted">Browser storage is unavailable. You can still create a world and export a backup.</p>';this.toast('Could not read local worlds.',err.message);}}
 exportSave(){if(!this.g.worldId)return;const data=this.g.snapshot(),blob=new Blob([JSON.stringify(data)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(this.g.worldName.replace(/[^a-z0-9_-]/gi,'_')||'world')+'.brocraft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);this.toast('Backup exported.','Keep this file to move your world between browsers.',22);}
 renderOptions(){const root=$('option-fields');root.replaceChildren();const specs=[['distance','Render distance',2,6,1,v=>`${v*2+1} × ${v*2+1} chunks`],['sensitivity','Mouse sensitivity',.35,2.8,.05,v=>Number(v).toFixed(2)+'×'],['fov','Field of view',60,100,1,v=>(v*Math.PI/180).toFixed(2)+' rad'],['volume','Master volume',0,1,.01,v=>Math.round(v*100)+'%'],['resolution','Render resolution',.6,1,.1,v=>Math.round(v*100)+'%']];for(const [key,label,min,max,step,format] of specs){const row=document.createElement('div');row.className='option-field';const id='opt-'+key;row.innerHTML=`<label for="${id}">${label}<output>${format(this.g.options[key])}</output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${this.g.options[key]}">`;row.querySelector('input').oninput=e=>{this.g.options[key]=Number(e.target.value);row.querySelector('output').textContent=format(this.g.options[key]);if(key==='volume')this.g.sound.applyOptions();if(key==='resolution')this.g.renderer.resize(this.g.options.resolution);if(key==='distance')this.g.updateStream(true);this.persistOptions();};root.appendChild(row);}const row=document.createElement('div');row.className='option-field option-toggle';row.innerHTML=`<label for="opt-bobbing">View bobbing</label><input id="opt-bobbing" type="checkbox" ${this.g.options.bobbing?'checked':''}>`;row.querySelector('input').onchange=e=>{this.g.options.bobbing=e.target.checked;this.persistOptions();};root.appendChild(row);}
 persistOptions(){try{localStorage.setItem('brocraft-options',JSON.stringify(this.g.options));}catch{}}
 createHotbar(){for(let i=0;i<9;i++){const el=document.createElement('div');el.className='slot';$('hotbar').appendChild(el);this.hotbarSlots.push(el);}for(let i=0;i<10;i++){const h=document.createElement('img');h.src=Assets.heart;h.alt='';h.className='vital full';$('hearts').appendChild(h);const f=document.createElement('img');f.src=Assets.food;f.alt='';f.className='vital full';$('hunger').appendChild(f);}this.refreshHotbar();}
 slotContent(s,hotkey=null){let html=hotkey!==null?`<span class="slot-key">${hotkey+1}</span>`:'';if(!s||!ITEMS[s.id])return html;html+=`<img draggable="false" src="${Assets.icons[s.id]}" alt="${escapeHTML(ITEMS[s.id].name)}">`;if(s.n>1)html+=`<span class="count">${s.n}</span>`;if(ITEMS[s.id].maxDurability){const pct=clamp(s.dur/ITEMS[s.id].maxDurability*100,0,100);html+=`<span class="durability"><i style="width:${pct}%;background:${pct<20?'#d59a67':'#bfd58c'}"></i></span>`;}return html;}
 refreshHotbar(){for(let i=0;i<9;i++){const el=this.hotbarSlots[i];el.innerHTML=this.slotContent(this.g.inventory[i],i);el.classList.toggle('selected',i===this.g.selected);}this.updateJourney();}
 showItemName(text=null){$('item-name').textContent=text||ITEMS[this.g.held()?.id]?.name||'Empty hand';$('item-name').style.opacity=1;}
 refreshHUD(){const g=this.g;if(!g.active)return;const p=g.player;const phase=mod(g.time,DAY_LENGTH)/DAY_LENGTH;const period=phase<.10?'Sunrise':phase<.38?'Daylight':phase<.52?'Sunset':phase<.94?'Night':'Dawn';$('world-label').textContent=g.worldName;$('biome-label').textContent=g.world.column(Math.floor(p.x),Math.floor(p.z)).biome;$('day-label').textContent=`Day ${Math.floor(g.time/DAY_LENGTH)+1} · ${period}`;$('clock-icon').textContent=g.daylight<.3?'☾':'☀';$('vitals').style.visibility=g.mode==='creative'?'hidden':'visible';$('hearts').setAttribute('aria-label',`${Math.ceil(p.health)} of 20 health`);$('hunger').setAttribute('aria-label',`${Math.ceil(p.hunger)} of 20 hunger`);for(let i=0;i<10;i++){for(const [id,value] of [['hearts',p.health],['hunger',p.hunger]]){const el=$(id).children[i];el.className='vital'+(value>i*2+1?' full':value>i*2?' half':'');}}$('air').textContent=g.mode==='survival'&&(p.underwater||p.air<19)?'○'.repeat(Math.ceil(p.air/2)):'';$('xp-line').firstChild.style.width=mod(g.xp,100)+'%';$('item-name').style.opacity=g.itemLabelTime>0?1:0;$('underwater').style.opacity=p.underwater?.65:0;$('damage').style.opacity=g.flash;$('position-label').textContent=g.mode==='creative'?(p.fly?'CREATIVE · FLYING':'CREATIVE · DOUBLE-TAP '+g.controls.label('jump').toUpperCase()+' TO FLY'):`${Math.floor(p.x)} / ${Math.floor(p.y)} / ${Math.floor(p.z)}`;
  const t=g.target,mt=g.mobTarget;if(!g.overlay&&(t||mt)){let title,sub;if(mt){title=MOB_TYPES[mt.type].name;sub=(MOB_TYPES[mt.type].hostile?'HOSTILE':'WILDLIFE')+' · '+Math.ceil(mt.hp)+' HEALTH';}else{const b=BLOCKS[t.id],tool=ITEMS[g.held()?.id];title=b.name;sub=b.station?'RIGHT-CLICK TO USE':b.id===28?'RIGHT-CLICK TO HARVEST':b.minTier&&(!tool||tool.tool!=='pick'||tool.tier<b.minTier)?'REQUIRES '+(['','WOOD','STONE','IRON','AETHER'][b.minTier])+' PICKAXE':b.tool?b.tool.toUpperCase()+' RECOMMENDED':'HOLD LEFT MOUSE TO GATHER';}$('target-info').style.display='block';$('target-info').innerHTML=escapeHTML(title)+`<small>${escapeHTML(sub)}</small>`;}else $('target-info').style.display='none';
  $('mine-meter').style.opacity=g.mine?1:0;$('mine-meter').firstChild.style.width=(g.mine?clamp(g.mine.progress*100,0,100):0)+'%';if(g.debug){const light=g.lightAt(p.x,p.y+1,p.z);$('debug').textContent=`BROCRAFT / ORIGINAL VOXEL ENGINE\n${Math.round(g.fps)} FPS · ${g.frameMs.toFixed(1)} ms\nXYZ ${p.x.toFixed(2)} / ${p.y.toFixed(2)} / ${p.z.toFixed(2)}\n${g.world.chunks.size} chunks · ${g.world.dirty.size} dirty · ${g.queue.length} queued\n${g.renderer.drawCalls} draws · ${Math.round(g.renderer.triangles/1000)}k triangles\n${g.mobs.length} creatures · ${g.drops.length} drops\nSky ${light.sky.toFixed(2)} · Local ${light.torch.toFixed(2)}\nSeed ${g.world.seed}\n${p.grounded?'GROUNDED':'AIRBORNE'} ${p.inWater?'SWIMMING':''}`;}}
 updateJourney(){const g=this.g;const steps=[['timber','Every adventure starts with a tree.','Hold left mouse to gather timber. Walk over drops to collect them.'],['tool','A little ingenuity goes a long way.',g.achievements.has('bench')?'Place your workbench. Use it to craft a wooden pickaxe.':'Press E. Make planks, sticks, and a workbench.'],['stone','Something stronger, just below.','Use your pickaxe to mine stone. Make stone tools and a furnace.'],['shelter','A place to call your own.','Place 12 blocks. Leave room inside for you, your workbench, and a torch.']];const index=steps.findIndex(s=>!g.achievements.has(s[0]));$('journey').classList.toggle('hidden',!g.showJourney||g.mode==='creative'||index<0);if(index>=0){$('journey-title').textContent=steps[index][1];$('journey-desc').textContent=steps[index][2];}for(let i=0;i<4;i++)$('journey-dots').children[i].classList.toggle('done',g.achievements.has(steps[i][0]));}
 bindFoley(){
  const g=this.g;
  for(const b of document.querySelectorAll('[data-studio-tab]'))b.onclick=()=>{
   const lab=b.dataset.studioTab==='world';$('score-studio').classList.toggle('hidden',lab);$('foley-lab').classList.toggle('hidden',!lab);
   for(const t of document.querySelectorAll('[data-studio-tab]')){t.classList.toggle('selected',t===b);t.setAttribute('aria-selected',String(t===b));}
   g.sound.foleySolo=lab&&$('lab-solo').checked;g.sound.tick();this.renderFoleyToggles();
  };
  $('lab-solo').onchange=()=>{g.sound.foleySolo=$('lab-solo').checked;g.sound.tick();};
  for(const b of document.querySelectorAll('[data-animal]'))b.onclick=()=>{g.sound.audition('animal',b.dataset.animal,{side:$('lab-position').value,state:$('lab-voice-state').value});$('lab-now').textContent=b.querySelector('strong').textContent+' / '+$('lab-voice-state').value;};
  $('lab-strike').onclick=()=>{const material=$('lab-material').value,action=$('lab-action').value;g.sound.audition('material',material,{side:$('lab-position').value,action,tool:$('lab-tool').value});$('lab-now').textContent=material+' / '+action+' / new variation';};
  for(const b of document.querySelectorAll('[data-foley-event]'))b.onclick=()=>{g.sound.audition('event',b.dataset.foleyEvent,{side:$('lab-position').value});$('lab-now').textContent=b.textContent;};
  $('soundcheck-world').onclick=()=>{if(g.active){this.toast('Save & quit to title first.','Your current world will not be replaced.');return;}g.sound.start();g.beginWorld(null,{name:'The listening glade',seed:'first-light',mode:'creative',soundcheck:true}).catch(e=>this.fatal(e));};
  this.renderFoleyToggles();
 }
 renderFoleyToggles(){
  const g=this.g,root=$('foley-toggles');if(!root)return;root.replaceChildren();
  for(const [key,label,detail] of [['spatialAudio','Directional stereo','Calls and impacts follow their position around you.'],['detailFocus','Give the world room','Close calls and breaking blocks briefly soften the score.'],['soundCaptions','Sound captions','Optional visual labels for world sounds and their direction.']]){
   const row=document.createElement('label');row.className='foley-toggle';row.innerHTML=`<span>${label}<small>${detail}</small></span><input type="checkbox" ${g.options[key]?'checked':''}>`;
   row.querySelector('input').onchange=e=>{g.options[key]=e.target.checked;g.sound.applyOptions();this.persistOptions();if(key==='soundCaptions'&&!e.target.checked)$('sound-captions').replaceChildren();};root.append(row);
  }
  $('soundcheck-world').disabled=g.active;$('soundcheck-world').textContent=g.active?'Return to title to create a soundcheck world':'Explore the listening glade →';
 }

 bindInventory(){
  $('close-inventory').onclick=()=>this.closeInventory(true);$('recipe-search').oninput=e=>{this.search=e.target.value.toLowerCase();this.renderBook();};$('recipes-tab').onclick=()=>{this.bookMode='recipes';this.renderBook();};$('catalog-tab').onclick=()=>{this.bookMode='catalog';this.renderBook();};
  $('inventory-panel').addEventListener('mousedown',e=>{const el=e.target.closest('[data-slot]');if(!el)return;e.preventDefault();if(e.button!==0&&e.button!==2)return;const ref=this.slots.get(el.dataset.slot);if(!ref)return;this.dragSource=el.dataset.slot;this.dragButton=e.button;if(e.shiftKey){this.quickMove(ref);this.dragSource=null;}else this.slotAction(ref,e.button);$('tooltip').style.display='none';});
  document.addEventListener('mouseup',e=>{if(!this.station||!this.dragSource)return;const el=e.target.closest?.('[data-slot]');if(el&&el.dataset.slot!==this.dragSource&&this.cursor){const ref=this.slots.get(el.dataset.slot);if(ref)this.slotAction(ref,this.dragButton);}this.dragSource=null;});
  document.addEventListener('mousemove',e=>{this.pointer={x:e.clientX,y:e.clientY};this.positionCursor();if(this.station&&!this.cursor){const el=e.target.closest?.('[data-slot]');if(el){const ref=this.slots.get(el.dataset.slot);this.showTooltip(ref,e.clientX,e.clientY);}else $('tooltip').style.display='none';}else $('tooltip').style.display='none';});
  $('inventory-screen').addEventListener('mousedown',e=>{if(e.target===$('inventory-screen')&&this.cursor){this.g.spawnDrop(this.g.player.x,this.g.player.y+1,this.g.player.z,this.cursor,{delay:1.5});this.cursor=null;this.refreshCursor();this.g.inventoryChanged();}});
 }
 openInventory(kind='craft',key=null){if(this.station)this.closeInventory(false);const g=this.g;this.station={kind,key};this.gridSize=kind==='workbench'?3:2;this.craftGrid=new Array(this.gridSize**2).fill(null);this.cursor=null;this.slots.clear();this.search='';$('recipe-search').value='';this.bookMode='recipes';this.chosenRecipe=RECIPES[0];g.overlay='inventory';g.mouseDown=false;g.rightDown=false;g.mine=null;g.keys.clear();document.exitPointerLock?.();$('inventory-screen').classList.remove('hidden');this.hideMenus();$('inventory-title').textContent=kind==='workbench'?'Workbench':kind==='furnace'?'Furnace':kind==='chest'?'Chest':'Inventory & crafting';$('inventory-eyebrow').textContent=kind==='workbench'?'A LITTLE INGENUITY':kind==='furnace'?'TURN UP THE HEAT':kind==='chest'?'A PLACE FOR EVERYTHING':'POCKET WORKSHOP';$('catalog-tab').classList.toggle('hidden',g.mode!=='creative');this.renderStation();$('main-slots').replaceChildren();$('inv-hotbar').replaceChildren();for(let i=9;i<36;i++)$('main-slots').appendChild(this.makeSlot('inv',i));for(let i=0;i<9;i++)$('inv-hotbar').appendChild(this.makeSlot('inv',i));this.refreshInventory();this.renderBook();this.message('Click or drag to move items. Right-click to split a stack.');g.sound.event(kind==='chest'?'chest-open':'cloth',{level:kind==='chest'?.65:.27});g.sound.play('ui');}
 closeInventory(lock=true){if(!this.station)return;this.g.sound.event(this.station.kind==='chest'?'chest-close':'cloth',{level:this.station.kind==='chest'?.62:.18});for(const s of [...this.craftGrid,this.cursor])if(s){const left=addStack(this.g.inventory,s);if(left)this.g.spawnDrop(this.g.player.x,this.g.player.y+.8,this.g.player.z,{...s,n:left},{delay:1});}this.craftGrid=[];this.cursor=null;this.station=null;this.slots.clear();this.dragSource=null;$('inventory-screen').classList.add('hidden');$('tooltip').style.display='none';$('cursor-item').style.display='none';this.g.overlay=null;this.g.mouseDown=false;this.g.rightDown=false;this.g.keys.clear();this.g.inventoryChanged();if(lock&&this.g.player.health>0)this.g.lockPointer();}
 makeSlot(group,index,cls=''){const el=document.createElement('div');el.className='slot '+cls;el.dataset.slot=group+':'+index;el.setAttribute('role','button');el.setAttribute('aria-label',group+' slot '+(index+1));this.slots.set(el.dataset.slot,{group,index,el});return el;}
 resolve(ref){if(!ref)return null;const arr=ref.group==='inv'?this.g.inventory:ref.group==='grid'?this.craftGrid:ref.group==='tile'?this.g.world.tiles.get(this.station?.key)?.slots:null;return arr?{arr,index:ref.index,s:arr[ref.index]}:null;}
 getStack(ref){if(ref?.group==='output'){const r=matchRecipe(this.craftGrid,this.gridSize);return r?stack(r.out,r.n):null;}return this.resolve(ref)?.s||null;}
 renderStation(){const area=$('station-area');area.replaceChildren();const kind=this.station.kind;
  if(kind==='furnace'){
   area.innerHTML='<span class="station-caption">SMELTING</span><div class="furnace-controls"><div class="furnace-left" id="furnace-left"></div><div><div class="furnace-progress"><i id="smelt-progress"></i><span id="smelt-percent">0%</span></div></div><div id="furnace-output"></div><div class="furnace-tip">INPUT → OUTPUT<br><br>Coal, charcoal, logs, planks, and sticks provide fuel.<br><br>One item takes 8 seconds.</div></div>';$('furnace-left').appendChild(this.makeSlot('tile',0));const fire=document.createElement('div');fire.id='furnace-fire';fire.className='furnace-fire';fire.textContent='♨';$('furnace-left').appendChild(fire);$('furnace-left').appendChild(this.makeSlot('tile',1));$('furnace-output').appendChild(this.makeSlot('tile',2,'craft-output'));
  }else if(kind==='chest'){area.innerHTML='<span class="station-caption">CHEST STORAGE</span><div class="chest-area"><div id="chest-slots" class="slots nine"></div></div>';for(let i=0;i<27;i++)$('chest-slots').appendChild(this.makeSlot('tile',i));}
  else{
   area.innerHTML='<span class="station-caption">'+(kind==='workbench'?'3 × 3 CRAFTING':'2 × 2 CRAFTING')+'</span>';
   if(kind!=='workbench'){const a=document.createElement('div');a.className='avatar-card';const canvas=document.createElement('canvas');canvas.width=32;canvas.height=46;a.appendChild(canvas);area.appendChild(a);this.avatar(canvas);}
   const wrap=document.createElement('div');wrap.className='craft-wrap';const grid=document.createElement('div');grid.className='craft-grid';grid.style.gridTemplateColumns=`repeat(${this.gridSize}, var(--slot))`;for(let i=0;i<this.gridSize**2;i++)grid.appendChild(this.makeSlot('grid',i));wrap.appendChild(grid);const arrow=document.createElement('span');arrow.className='craft-arrow';arrow.textContent='→';wrap.appendChild(arrow);wrap.appendChild(this.makeSlot('output',0,'craft-output'));area.appendChild(wrap);
  }
 }
 avatar(canvas){const c=canvas.getContext('2d');const r=(x,y,w,h,color)=>{c.fillStyle=color;c.fillRect(x,y,w,h);};r(10,1,12,12,'#a8825d');r(10,1,12,4,'#64513a');r(10,5,2,6,'#8b694c');r(12,7,2,2,'#e7dfbb');r(18,7,2,2,'#e7dfbb');r(13,7,1,2,'#334c3c');r(18,7,1,2,'#334c3c');r(14,11,4,1,'#765239');r(8,14,16,17,'#5c8064');r(8,14,3,17,'#42684e');r(5,14,3,17,'#b68b64');r(24,14,3,17,'#b68b64');r(11,14,10,3,'#a7b88b');r(9,31,6,12,'#5c695f');r(17,31,6,12,'#69736a');r(9,42,6,3,'#4a4e40');r(17,42,6,3,'#4a4e40');r(7,44,18,1,'#91a07d');}
 refreshInventory(){if(!this.station)return;for(const ref of this.slots.values())ref.el.innerHTML=this.slotContent(this.getStack(ref),ref.group==='inv'&&ref.index<9?ref.index:null);this.refreshCursor();this.refreshRecipeDetail();}
 refreshStation(){if(!this.station)return;if(this.station.kind==='furnace'){const t=this.g.world.tiles.get(this.station.key);if(!t)return;$('smelt-progress').style.width=clamp(t.progress/8*100,0,100)+'%';$('smelt-percent').textContent=Math.floor(t.progress/8*100)+'%';$('furnace-fire').classList.toggle('lit',t.fuel>0);$('furnace-fire').title=t.fuel>0?Math.ceil(t.fuel)+' seconds of fuel remaining':'Add fuel to the lower slot';const signature=JSON.stringify(t.slots);if(signature!==this.lastStationSignature){this.lastStationSignature=signature;this.refreshInventory();this.g.ui.refreshHotbar();}}}
 accepts(ref,s){if(!s)return true;if(ref.group==='output')return false;if(ref.group==='tile'&&this.station.kind==='furnace'){if(ref.index===2)return false;if(ref.index===1)return !!ITEMS[s.id].fuel;}return true;}
 slotAction(ref,button){if(ref.group==='output'){this.craft(false);return;}const slot=this.resolve(ref);if(!slot)return;let s=slot.s;
  if(this.station.kind==='furnace'&&ref.group==='tile'&&ref.index===2){if(!s)return;if(!this.cursor){const n=button===2?Math.ceil(s.n/2):s.n;this.cursor={...s,n};s.n-=n;if(!s.n)slot.arr[slot.index]=null;}else if(sameStack(this.cursor,s)){const n=Math.min(button===2?1:s.n,ITEMS[s.id].stack-this.cursor.n);this.cursor.n+=n;s.n-=n;if(!s.n)slot.arr[slot.index]=null;}this.changed();return;}
  if(!this.cursor){if(s){const n=button===2?Math.ceil(s.n/2):s.n;this.cursor={...s,n};s.n-=n;if(!s.n)slot.arr[slot.index]=null;}}
  else if(!this.accepts(ref,this.cursor)){this.message('That slot needs fuel: coal, charcoal, wood, or sticks.');return;}
  else if(button===2){if(!s){slot.arr[slot.index]={...this.cursor,n:1};if(--this.cursor.n===0)this.cursor=null;}else if(sameStack(s,this.cursor)&&s.n<ITEMS[s.id].stack){s.n++;if(--this.cursor.n===0)this.cursor=null;}}
  else if(!s){slot.arr[slot.index]=this.cursor;this.cursor=null;}
  else if(sameStack(s,this.cursor)){const n=Math.min(this.cursor.n,ITEMS[s.id].stack-s.n);s.n+=n;this.cursor.n-=n;if(!this.cursor.n)this.cursor=null;}
  else{slot.arr[slot.index]=this.cursor;this.cursor=s;}
  this.changed();
 }
 changed(){this.g.sound.play('ui');this.g.inventoryChanged();this.refreshStation();}
 quickMove(ref){if(ref.group==='output'){this.craft(true);return;}const source=this.resolve(ref);if(!source?.s)return;const original={...source.s};let left=original.n;
  if(ref.group==='inv'&&this.station.kind==='chest')left=addStack(this.g.world.tiles.get(this.station.key).slots,original);
  else if(ref.group==='inv'&&this.station.kind==='furnace'&&(SMELTS[original.id]||ITEMS[original.id].fuel)){const idx=SMELTS[original.id]?0:1,t=this.g.world.tiles.get(this.station.key),arr=[t.slots[idx]];left=addStack(arr,original);t.slots[idx]=arr[0];}
  else if(ref.group==='inv'){const start=ref.index<9?9:0,end=ref.index<9?36:9,arr=this.g.inventory.slice(start,end);left=addStack(arr,original);for(let i=start;i<end;i++)this.g.inventory[i]=arr[i-start];}
  else left=addStack(this.g.inventory,original);
  if(left===0)source.arr[source.index]=null;else source.arr[source.index].n=left;this.changed();}
 craft(many=false){if(!['craft','workbench'].includes(this.station?.kind))return;let crafted=0,last=null;for(let n=0;n<(many?64:1);n++){const r=matchRecipe(this.craftGrid,this.gridSize);if(!r)break;const result=stack(r.out,r.n);if(many){const trial=this.g.inventory.map(cloneStack);if(addStack(trial,result)>0){this.message('Your backpack is full. Make room for the result.');break;}this.g.inventory=trial;}else{if(!this.cursor)this.cursor=result;else if(sameStack(this.cursor,result)&&this.cursor.n+result.n<=ITEMS[result.id].stack)this.cursor.n+=result.n;else{this.message('Place the item you are holding before taking this result.');break;}}
   for(let i=0;i<this.craftGrid.length;i++)if(this.craftGrid[i]&&--this.craftGrid[i].n===0)this.craftGrid[i]=null;crafted+=r.n;last=r;if(r.out>=200)this.g.award('tool');if(r.out===20)this.g.award('bench');this.g.xp+=2;
  }if(crafted){this.g.sound.play('craft');this.message(`Made ${crafted} × ${ITEMS[last.out].name}.`);this.g.inventoryChanged();this.renderBook();}}
 fillRecipe(r){if(!this.station||!['craft','workbench'].includes(this.station.kind))return;const cost=recipeCost(r),pool=[...this.g.inventory.map(cloneStack),...this.craftGrid.map(cloneStack)];if(r.pattern.length>this.gridSize||r.pattern[0].length>this.gridSize){this.message('This recipe needs the 3 × 3 grid of a workbench.');return;}for(const [id,n] of Object.entries(cost))if(countItem(pool,Number(id))<n){this.message('Not enough '+ITEMS[id].name+'.');return;}for(const [id,n] of Object.entries(cost))removeItems(pool,Number(id),n);this.g.inventory=pool.slice(0,36);for(const s of pool.slice(36))if(s){const left=addStack(this.g.inventory,s);if(left)this.g.spawnDrop(this.g.player.x,this.g.player.y+.8,this.g.player.z,{...s,n:left});}this.craftGrid.fill(null);for(let y=0;y<r.pattern.length;y++)for(let x=0;x<r.pattern[y].length;x++)if(r.pattern[y][x])this.craftGrid[y*this.gridSize+x]=stack(r.pattern[y][x]);this.message('Ingredients placed. Click the result on the right to craft.');this.g.inventoryChanged();}
 renderBook(){if(!this.station)return;$('recipes-tab').classList.toggle('active',this.bookMode==='recipes');$('catalog-tab').classList.toggle('active',this.bookMode==='catalog');$('recipe-list').replaceChildren();$('recipe-search').placeholder=this.bookMode==='catalog'?'Search every block & item…':'Find something to make…';
  if(this.bookMode==='catalog'&&this.g.mode==='creative'){
   for(const d of Object.values(ITEMS).filter(d=>d.name.toLowerCase().includes(this.search))){const el=document.createElement('button');el.className='recipe-entry';el.innerHTML=`<img alt="" src="${Assets.icons[d.id]}"><span>${escapeHTML(d.name)}<small>${d.tool?'Tool':d.place?'Building block':'Item'}</small></span><b>∞</b>`;el.onclick=e=>{const s=stack(d.id,d.stack);if(e.shiftKey){const left=addStack(this.g.inventory,s);if(left)this.message('Backpack full. Put a stack down first.');}else this.cursor=s;this.g.inventoryChanged();this.message('Place this stack in your backpack or quick-access bar.');};$('recipe-list').appendChild(el);}$('recipe-detail').innerHTML='Unlimited materials. Click to pick up a stack. Shift-click to add it to your backpack. Double-tap your jump key outside this menu to fly.';return;
  }
  if(this.station.kind==='furnace'){for(const [input,output] of Object.entries(SMELTS)){const d=ITEMS[output];if(!(d.name+' '+ITEMS[input].name).toLowerCase().includes(this.search))continue;const el=document.createElement('button');el.className='recipe-entry';el.innerHTML=`<img alt="" src="${Assets.icons[output]}"><span>${escapeHTML(d.name)}<small>Smelt ${escapeHTML(ITEMS[input].name)}</small></span><b>→</b>`;el.onclick=()=>{const t=this.g.world.tiles.get(this.station.key),id=Number(input);if(countItem(this.g.inventory,id)<1){this.message('You need '+ITEMS[id].name+' in your backpack.');return;}if(t.slots[0]&&t.slots[0].id!==id){this.message('Empty the furnace input slot first.');return;}if(t.slots[0]?.n>=64)return;removeItems(this.g.inventory,id,1);if(t.slots[0])t.slots[0].n++;else t.slots[0]=stack(id);this.g.inventoryChanged();this.message('Input added. Put coal or wood in the lower slot for fuel.');};$('recipe-list').appendChild(el);}$('recipe-detail').innerHTML='<strong>Heat makes all the difference.</strong><br>Input above, fuel below, result on the right. Furnaces keep working while you explore, as long as the world is running.';return;}
  let entries=0;for(const r of RECIPES){if(!r.name.toLowerCase().includes(this.search))continue;const fits=r.pattern.length<=this.gridSize&&r.pattern[0].length<=this.gridSize,available=Object.entries(recipeCost(r)).every(([id,n])=>countItem([...this.g.inventory,...this.craftGrid],+id)>=n);const el=document.createElement('button');el.className='recipe-entry'+(this.chosenRecipe===r?' chosen':'');el.innerHTML=`<img alt="" src="${Assets.icons[r.out]}"><span>${escapeHTML(r.name)}<small>${!fits?'Needs a workbench':r.group}</small></span><b>${available&&fits?'✓':r.n>1?'×'+r.n:''}</b>`;el.onclick=()=>{this.chosenRecipe=r;this.renderBook();};$('recipe-list').appendChild(el);entries++;}if(!entries)$('recipe-list').innerHTML='<p class="muted" style="color:#6a7f56">No matching recipes.</p>';this.refreshRecipeDetail();}
 refreshRecipeDetail(){if(!this.station||this.bookMode==='catalog'||this.station.kind==='furnace')return;const r=this.chosenRecipe;if(!r)return;const cost=recipeCost(r),fits=r.pattern.length<=this.gridSize&&r.pattern[0].length<=this.gridSize,allowed=['craft','workbench'].includes(this.station.kind),available=Object.entries(cost).every(([id,n])=>countItem([...this.g.inventory,...this.craftGrid],+id)>=n);$('recipe-detail').innerHTML=`<strong>${escapeHTML(r.name)}${r.n>1?' ×'+r.n:''}</strong><br>`+Object.entries(cost).map(([id,n])=>`${n} × ${escapeHTML(ITEMS[id].name)} <span style="opacity:.65">(${countItem([...this.g.inventory,...this.craftGrid],+id)} available)</span>`).join('<br>')+`<button id="fill-recipe" ${fits&&available&&allowed?'':'disabled'}>${!allowed?'Open your crafting inventory':!fits?'Requires a workbench':!available?'Gather the ingredients':'Fill crafting grid →'}</button>`;$('fill-recipe').onclick=()=>this.fillRecipe(r);}
 refreshCursor(){if(!this.cursor){$('cursor-item').style.display='none';return;}$('cursor-item').style.display='block';$('cursor-item').innerHTML=`<img alt="" src="${Assets.icons[this.cursor.id]}">${this.cursor.n>1?`<b>${this.cursor.n}</b>`:''}`;this.positionCursor();}
 positionCursor(){$('cursor-item').style.left=this.pointer.x+'px';$('cursor-item').style.top=this.pointer.y+'px';}
 showTooltip(ref,x,y){const s=this.getStack(ref);if(!s){$('tooltip').style.display='none';return;}const d=ITEMS[s.id];let detail=d.maxDurability?`${s.dur} / ${d.maxDurability} durability<br>${d.damage.toFixed(1)} attack damage · ${d.speed}× mining speed`:d.food?`Restores ${d.food} hunger`:d.station?'Place, then right-click to use':d.fuel?`${d.fuel} seconds of furnace fuel`:d.place?'Place with right mouse':'Crafting material';$('tooltip').innerHTML=`<strong>${escapeHTML(d.name)}</strong><small>${detail}</small>`;$('tooltip').style.display='block';$('tooltip').style.left=clamp(x+15,5,innerWidth-240)+'px';$('tooltip').style.top=clamp(y+17,5,innerHeight-110)+'px';}
 message(text){$('inventory-message').textContent=text;}
}
function boot(){try{makeAssets();const renderer=new Renderer($('game'));const game=new Game(renderer);const ui=new UI(game);globalThis.BroCraft={game,ui,version:'1.2-living-world',engine:BC};requestAnimationFrame(t=>game.frame(t));}catch(error){console.error(error);$('error-screen').classList.remove('hidden');$('error-text').textContent=error.message||String(error);}}
boot();
